### ISSUE TITLE
Hyjal Instance

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#1]
This is script issue as spawns & DB issue on flying waves as movement..
and i posted it on script dev 2 also..
Waves start in rong spawn points to close to alliance and horde base...
Waves start to fast..like 12-13 seconds after last wave mob dies..leaving no time for raid to get rdy
Flying waves in horde base...start in same position as ground waves...and the creeps r not flying but walking

**Comment by Salja** [comment]
"Waves start to fast..like 12-13 seconds after last wave"

you have a right timer for this ? video from youtube etc ?

"This is script issue as spawns & DB issue on flying waves as movement.."
I will check it

"Flying waves in horde base...start in same position as ground waves...and the creeps r not flying but walking"

test with last "dev" db from repo i have fixed a lot about this not sure this but over this problem

**Comment by Mibu86** [comment]
sorry for absence..gonna test it

**Comment by Salja** [comment]
btw for timer you can look here and change it for testing https://github.com/CoronaCore/Scripts/blob/master/scripts/kalimdor/caverns_of_time/hyjal/hyjalAI.cpp#L147

**Comment by Salja** [comment]
i hope on next week i can work some more on tbc wehn im complete my work on cata and classic

**Comment by Salja** [comment]
new report here https://github.com/CoronaCore/Issues/issues/27
