### ISSUE TITLE
Quest:The Scryer's Scryer (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#100]
http://www.wowhead.com/quest=11490
Everything works...but quest do-sent complete at the end of cinematic

**Comment by Salja** [comment]
Fixed

**Comment by Salja** [comment]
most fixed tbc source ? what you mean ?

**Comment by Mibu86** [comment]
huh?

**Comment by Salja** [comment]
I mean what you think is coronacore the most fixed tbc core or is other better

**Comment by Mibu86** [comment]
i think this is the most Fixxed mangos TBC core... dunno wut core this guy's are using... https://hellground.net 
But even if they use Mangos ..i don't think they are going to share fixxes
But yes i think so..and if u keep fixing all keep posting you bugs till we get this fixxed and working...

**Comment by Salja** [comment]
The hellground core is open source http://tbc-core.hellground.net/ you can try it have a lot of more Bugs and its a trinity fork not a mangos

**Comment by Mibu86** [comment]
then this is the most fixxed? :D

**Comment by Salja** [comment]
I think we have  in moment the best active support and most db fixes and most working quests and events, maybe other are more other things fixed but the most gameplay come wehn npc say textes moves and not stay on same place so other server fix spells etc. But not quest working xD :-)

**Comment by Mibu86** [comment]
well Eventually ure gonna have to fix the core issues on spells :P (lot's of them)
Also i think all start posting Class Talent and Spell bugs soon..
But i need time for testing them bit by bit...
Also how is Hyjal doing?
Ps: dont hurry :)  i know ure just one person

**Comment by Salja** [comment]
Hyjal need more testing you says works on mangos wotlk better as tbc so i think on weekend i will setup a small server so you can join and we can test it step by step

**Comment by Salja** [comment]
Pls more quest reports need more xD :-)

**Comment by Mibu86** [comment]
lool
