### ISSUE TITLE
(Other)Question..

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#103]
How to fix this console error for a custom item..just asking...dunno were to list it

ERROR:Item (Entry: 60001) not correct (not listed in list of existing items)

**Comment by Salja** [comment]
I think is list in dbc files never i create a custom item but use a entry from other item i think will work

**Comment by Mibu86** [comment]
strange i am used creating custom items...and i make them so perfectly that i never got this error before..is possible that ure right  and the new core checks inside the dbc..
One more thing...since were talking custom..i just finished creating a Alterac Valley Mark of Honor
http://www.wowhead.com/item=20560
Custom Vendor since for low population is kinda impossible for players to win that batlleground and obtain the mark...(it was a pain! creating the npc..adding entry in vendor template etc...finished without errors..).
Ever considered to add such a custom npc inside the db? for the small population servers?
And the new http://wow-v.com tool ...is messed up now with the new DB columns..so i had to do it by hand...know any compatible tool?(for the future)

**Comment by Salja** [comment]
I will look wehn im on pc in 2 houers than i can you say more

**Comment by Mibu86** [comment]
Here are 2 SS with my custom Alterac Valley mark fix :P 
![wowscrnshot_071214_092801](https://cloud.githubusercontent.com/assets/6356589/3560799/cd749966-098d-11e4-9ad6-182b3021baa0.jpg)
![wowscrnshot_071214_092823](https://cloud.githubusercontent.com/assets/6356589/3560800/d697ee8a-098d-11e4-84b4-33bc610ce779.jpg)

**Comment by Salja** [comment]
I cant add custom npc in db but i plan to add a new repo for custom sql files i create some time ago tier vendors so i can upload it and than you can tell me what you npc all needed we can add all to the extra repo than you can easy insert after db reinstall.

About the item i have no idea check dbc or not i think it but never check it xD :-) you can try to use lower item entry of item.

About tool at the moment nothing tool support new mangos creature template struck but i think me and daniel cqn create a complete new tool in next time
