### ISSUE TITLE
Boss/Game Object: The Lurker Below ..SSC (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#104]
![wowscrnshot_071214_114831](https://cloud.githubusercontent.com/assets/6356589/3561009/7e70e356-09a1-11e4-80da-7a0265ef3a91.jpg)
Hes not supposed to be already spawned...
Here details:http://www.wowhead.com/npc=21217#comments
.....
In order to access the boss, he must be fished out of the "Strange Pool" where he is located.
There should be a water pool there..
Edit: an it is..under the boss...

**Comment by Salja** [comment]
Fixed close
