### ISSUE TITLE
(Visual Targets)BT ..(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#105]
Dont ask me the name ...
![wowscrnshot_071214_221431](https://cloud.githubusercontent.com/assets/6356589/3562788/fb241268-0a07-11e4-897b-36788d92ab99.jpg)
![wowscrnshot_071214_221419](https://cloud.githubusercontent.com/assets/6356589/3562791/0fe9378c-0a08-11e4-981c-624bfd524416.jpg)

**Comment by Salja** [comment]
Its bad wehn have no name xD :-) you can not select him ?

**Comment by Mibu86** [comment]
nope

**Comment by Salja** [comment]
Ok sounds like some bt rewirte xD :-)

**Comment by Salja** [comment]
Fixed

**Comment by Salja** [comment]
Give all and report this night much than i can fix it tomorrow xD :-)
