### ISSUE TITLE
Quest: Against the Legion(missing drop)(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#108]
http://www.wowhead.com/quest=10641
Quest item dosent drop...the rest work's i tested..after i added the item to me...
The missing item should drop from :
Wrath Priestess
http://www.wowhead.com/npc=18859
this is it : 
Freshly Drawn Blood
http://www.wowhead.com/item=30850

**Comment by Mibu86** [comment]
..same place as https://github.com/CoronaCore/Issues/issues/82 have u looked for that spell trigger?

**Comment by Salja** [comment]
tomorrow i will fix it today look german XD

**Comment by Mibu86** [comment]
lol

**Comment by Salja** [comment]
Goallllllll

**Comment by Salja** [comment]
Fixed
