### ISSUE TITLE
Instance: Arcatraz(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#112]
The Protean (npc) is fighting the Arcatraz Guards...etc(humanoids)
![wowscrnshot_071414_082133](https://cloud.githubusercontent.com/assets/6356589/3567323/e55f7fd4-0b16-11e4-833c-a8861d967d20.jpg)

**Comment by Mibu86** [comment]
More Bugs...the Guards at "Stasis Bloc Maximus"  just spamming chain lighting at me..over and over again.
![wowscrnshot_071414_082732](https://cloud.githubusercontent.com/assets/6356589/3567353/c46263ae-0b17-11e4-837a-2de9f6f64424.jpg)
without coming to life

**Comment by Mibu86** [comment]
more..
Millhouse Manastorm gossip (talking)
onlly the last 2 lines appear on his head as /yell (but all gossip apears on chat..and sound
![wowscrnshot_071414_083314](https://cloud.githubusercontent.com/assets/6356589/3567384/e545b1ec-0b18-11e4-8d98-e3178a8461dc.jpg)

**Comment by Mibu86** [comment]
Serios last boss BUG
Harbinger Skyriss
http://www.wowhead.com/npc=20912
Issue: after u get afllicted by his Fear spell: http://www.wowhead.com/spell=39415 (Fear)
U are unable to attack him...via psihical dmg or spellcast..not even the "Finger of death" spell from the test item didint damaged him.
![wowscrnshot_071414_084038](https://cloud.githubusercontent.com/assets/6356589/3567423/c5e7e2ec-0b19-11e4-9ad5-f096843904e2.jpg)

**Comment by Salja** [comment]
must be fixed i close here reopen when not is
