### ISSUE TITLE
(other)Dual Accounting in Batlegrounds (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#121]
![wowscrnshot_071514_061020](https://cloud.githubusercontent.com/assets/6356589/3580077/aa9e37b6-0bcd-11e4-8699-6311de0b1571.jpg)
![wowscrnshot_071514_061027](https://cloud.githubusercontent.com/assets/6356589/3580078/aec450b4-0bcd-11e4-8b75-823d90f0a144.jpg)
..any way we can limit battleground instance to 1 char per ip so we can cut down the dual boxing stuff?

**Comment by ghost** [comment]
you would have to modify the core to do that. i would suggest to implement a condition before the player gets the queue pop, so he has to wait until the player with the same ip leaves the bg.
the players ip address are stored in the database and are loaded into the users current worldsession.

i made a code example for you, how it could look: https://gist.github.com/tyraela/bb1fa1468ad6d16b85bf (not finished, nor tested)

maybe salja implements your feature into the core with a option for you to enable it.

**Comment by Mibu86** [comment]
All wait to see wut he replays ...this would be a good thing to implement ..not just to Battlegrounds but to Arenas as well..

**Comment by Salja** [comment]
can be done by a lua script with :GetPlayerIP() - Returns the player's IP Address
better you ask in emudevs forum for a script or must wait what i have more time XD my todo list is atm very very big =(

**Comment by Salja** [comment]
i see a big problem what is wehn friends come and play all over same ip than ? XD

**Comment by ghost** [comment]
yeah then you have to wait until your friend with the same ip leaves the bg before you get an invite...
not sure if its the right approach to fix multiboxer issue.
