### ISSUE TITLE
Missing  Item: Tooth Pick (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#132]
=))
http://www.wowhead.com/item=37604#comments
The spell is in the database...
Sparkling Smile   http://www.wowhead.com/spell=49007
![wowscrnshot_071514_090708](https://cloud.githubusercontent.com/assets/6356589/3581189/4af79956-0be6-11e4-90f2-1f9e0e3aad4f.jpg)

**Comment by Salja** [comment]
fixed
