### ISSUE TITLE
(Other Request) New Branch (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#133]
If is not to much to ask...since every time u update the core i update mine...
I always have make manual fixes in other for a success merge of my core..
Can u pls make a different branch for my self...that would contain
Develop + Warden + Broadcast branches   /all in one for myself...
I know is a lil selfish but would greatly help speed up things for me..and more free time for searching bugs...

**Comment by Salja** [comment]
I think i can make in next days yes but next 2 days i have much rl work than im back for you xD :-)

**Comment by Mibu86** [comment]
I have to merge them again  today :| ..
..zipped...
come back fast i wunt FIXES
I did Everything Right the third time....compiling goes 100% perfect no errors..
But the second anyone logs in... server crashes... with error C0000005 ACCESS_VIOLATION 
Back on my core...i quit trying...those eluna Sync's are causing it...and i have no idea were is the issue..i dropped those updates..and core is running smooth now...

**Comment by Salja** [comment]
chrashes fixed

**Comment by Salja** [comment]
here warden and broadcaster branch https://github.com/vanilla-wow/OneServer/tree/AIO  i will only update for you

**Comment by Salja** [comment]
you on the pic ?

**Comment by Mibu86** [comment]
Ps:no longer fired :))
edit: or drunk

**Comment by Mibu86** [comment]
U did smth Rong to that compile....if Warden is on....FRames and Lagg..and it spams a certain Warden error in the console...over and over again ...that might be causing the spikes,frames and lagg....i disabled Warden atm...and it works good

**Comment by Salja** [comment]
Nothing is changed on warden branch

**Comment by Mibu86** [comment]
https://github.com/vanilla-wow/OneServer/tree/AIO here....this core compiled...with Warden on..
it haz spikes,,

**Comment by Salja** [comment]
I will test self tomorrow

**Comment by Mibu86** [comment]
k...it works fine with warden disabled
