### ISSUE TITLE
Fix item Thistle Tea for Classic.

### ISSUE THREAD

**Issue by zwisus** [CoronaCore/Issues#14]
PreTBC

Thistle Tea
Classes: Rogue
Requires Level 5
Use: Instantly restores 100 energy. (cooldown 5 min)

http://paste2.org/UYk0NK9f

**Comment by Salja** [comment]
hmm the ingame tooltip says 1 mins cooldown ?

**Comment by zwisus** [comment]
5 mins

**Comment by Salja** [comment]
hmm strange http://www.imgbox.de/users/public/images/t0o8qqTPby.jpg

**Comment by zwisus** [comment]
http://www.wowwiki.com/Thistle_Tea?oldid=289112

For zeroserver

**Comment by Salja** [comment]
ok i see the item have the cooldown not the spell thanks i will add

**Comment by Salja** [comment]
Thanks
