### ISSUE TITLE
Confused and fleeing

### ISSUE THREAD

**Issue by zwisus** [CoronaCore/Issues#15]
1.
when Confused or fleeing Finalize,the player don't stop moving sometime.
http://paste2.org/0jD6ztJs

2.
case 1
when a creature has aura(19503 or 118),it can add threat and follow the healer.
only follow the healer ,can not attcak.

spell:
19503= Scatter Shot
118= Polymorph

case 2
If hunter has a pet.
hunter and his pet in creature‘s Aggro.
hunter cast Scatter Shot to creature, at the same time cast Feign Death)
when the Scatter Shot's aura remove from the creature,
the creature will stop attack,only to follow the pet,only follow,can not attcak.
Not only Scatter Shot(confuse), Polymorph and Fear too.

I think mobs has Confused and fleeing aura can MoveChase is wrong.
http://paste2.org/4wLWbHJa

**Comment by Salja** [comment]
hmm im not 100% sure here i think thats need some more checks befor i will poke some other devs to look at it thanks

**Comment by Salja** [comment]
need testing
https://github.com/CoronaCore/ZeroServer/commit/633f0da66da04516238b4738d1590dfb512aa849

**Comment by zwisus** [comment]
when Confused or fleeing Finalize,the player don't stop moving sometime.
http://paste2.org/0jD6ztJs

**Comment by Salja** [comment]
Thanks i not close here wait of feedback

**Comment by Salja** [comment]
unit.InterruptMoving(); is sice some time on dev branch unit.StopMoving();

https://github.com/CoronaCore/ZeroServer/commit/97f841b4a4d44e70d439312d17d7fe217405696e

**Comment by Salja** [comment]
I think working fine now wehn not pls poke me than i make it reopen here
