### ISSUE TITLE
Npc:Netherwing Ally (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#150]
http://www.wowhead.com/npc=23320#comments
Summoned by  on-use abilities of the Commander's Badge, Captain's Badge,Overseer's Badge
Should be casting Arcane Bolts can do 450-600 damage and can do about 6 of them limited by his mana pool.
Issue: do-sent cast anything it just attack's with psihical

**Comment by Salja** [comment]
Must be fixed when nit reopen
