### ISSUE TITLE
Development Branch   .reload command(mangos one/other)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#157]
I found this patch ...for mangos one.. i believe is old..but it would be a good thing not having to restart my server every time i upgrade Database

here is the patch...
http://uploadkon.ir/fl/d/MjU1Njk%3D
it should allow the 
.reload of item,gameobject and creature templates without server restart

**Comment by Salja** [comment]
Here a old discuss over reload templates is not saved and can break your server https://www.getmangos.eu/oldcore-modifications/3670-implemented-reload-creature_template.html?highlight=Reload+creature+template

**Comment by Mibu86** [comment]
yep ..got it... :(
