### ISSUE TITLE
(visible target)Eclipse Point .... (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#165]
![wowscrnshot_072414_072114](https://cloud.githubusercontent.com/assets/6356589/3683637/0fddb534-12ea-11e4-862a-8dc580a1c3e6.jpg)

**Comment by Salja** [comment]
Today i have buxed a second mac pc xD :-) i will setup as server system and will install a test server on it so we can start testing hyjal and rewirte it so pls give me 1-2 days for new fixes

**Comment by Mibu86** [comment]
well since 27 till 31 i got re-exams i need to attend to...i do hope to be @ when u start it...maybe i can help with the issues and pinpoint them..
