### ISSUE TITLE
(Quest) Brother Against Brother (Mangos One)

### ISSUE THREAD

**Issue by kalel76300** [CoronaCore/Issues#166]
Interacting with the quest NPC, Lakka (#18956), does not initiate any event in which he is freed from the cage he is in. Cannot complete quest.

**Comment by Mibu86** [comment]
closed because? ..did u retested it? was i wrong?

**Comment by Salja** [comment]
Maybe mistake on button click ?

**Comment by Mibu86** [comment]
lol!

**Comment by Salja** [comment]
But nice to see more ppls use corona

**Comment by Mibu86** [comment]
Use search button https://github.com/CoronaCore/Issues/issues/116
