### ISSUE TITLE
64 bits?

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#17]
For the one emulator?

**Comment by Salja** [comment]
What Problem for 64x works fine

**Comment by Mibu86** [comment]
no problem at all...m asking because i wanna compile it in 32 bits....any issues i might have?
Also i was very busy with hightscool..and m still in exams session .. so if ure wondering..i just shut-ed down the pc and abandoned all project..just poped up again to restart everything..
I merged all the branches in one emu...last time ..only had 1 playerbot issue spaming Playerbot is not enable wen it was disabled...by any npc a player would click on..but if m gonna have it again all contact you

**Comment by Salja** [comment]
can close here ?
