### ISSUE TITLE
(0ther)When do we start working again...(mangos 1)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#170]
? m busy with school as i said..but i can still find lil time.. i think..wut's urea excuse?

**Comment by Salja** [comment]
Tdday xD :-) on weekend i have maked some other things

**Comment by Salja** [comment]
Tomorrow i start today i have much rl

**Comment by Salja** [comment]
I work today some but not done yet pls wait of tomorrow for update your core

**Comment by Salja** [comment]
ok now done you can use it

**Comment by a6607890** [comment]
why stop zero program？complicated？ can u send the code to me？ my email address：xyhw168@126.com thax alot ：-）

**Comment by Salja** [comment]
Well to much working on classic and wotlk so i thing not needed what i make this xD :-) but you can xheck here theluda make classic core with eluna and more https://bitbucket.org/mangoszero
