### ISSUE TITLE
Pet Mana error

### ISSUE THREAD

**Issue by q67732896** [CoronaCore/Issues#172]
The first summon pets, pets have mana
The second summon pet, it becomes a rage
Warlock, Mage, there is this error

![1](https://cloud.githubusercontent.com/assets/8146824/3865728/e2461fac-1fa6-11e4-836a-1ffe62c9b863.jpg)
![2](https://cloud.githubusercontent.com/assets/8146824/3865738/76bf5752-1fa7-11e4-8c7a-457be0c7ff1e.jpg)

**Comment by Salja** [comment]
Thanks

**Comment by Mibu86** [comment]
lol

**Comment by Salja** [comment]
Lol what ? Tell use xD :-)

**Comment by q67732896** [comment]
I found a solution
creature_template Entry：416 UnitClass：1 
Modify：Entry：416 UnitClass：2
Pet Mana normal

**Comment by Salja** [comment]
Yes sice the new stats system a lot of unitclasses are worng

**Comment by Salja** [comment]
Update creature_template set UnitClass=2 where entry =416;

**Comment by a6607890** [comment]
thx a lot

------------------ 原始邮件 ------------------
发件人: "q67732896";notifications@github.com;
发送时间: 2014年8月10日(星期天) 下午2:39
收件人: "CoronaCore/Issues"Issues@noreply.github.com; 

主题: Re: [Issues] Pet Mana error (#172)

I found a solution
 creature_template Entry：416 UnitClass：1 
 Modify：Entry：416 UnitClass：2
 Pet Mana normal

**Comment by Salja** [comment]
Will be fix in next push wehn im done with my other things, thanks for reporting

**Comment by Salja** [comment]
I check it the right UnitClass for this NPC is 8

UPDATE creature_template SEt UnitClass = 8 WHERE entry = 416;

I have worked on all UnitClass what make Error on StartUp pls test it and give me feedback only 1 npc have startup error now
http://pastebin.com/diL6P4Fq

**Comment by q67732896** [comment]
THX

**Comment by Salja** [comment]
My database server is atm offline to dump my db i will add in main db in next few days

**Comment by Salja** [comment]
Have someone tested ?

**Comment by Salja** [comment]
Pushed
