### ISSUE TITLE
TestServer 

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#173]
I will setup in next days a small test server i hope some ppls here will help than to check few things i will complete in next time all 5er instances so i hope few ppls will help me than pls reply here wehn you will help

**Comment by Mibu86** [comment]
m in..

**Comment by Salja** [comment]
Ok test server is setup now send me a email with account name and password i send email back with all other datas so we can start testing and fixing instances salja8840@gmail.com

**Comment by Salja** [comment]
Bump 3 testers we have nice i hope some come more we are on alliance side
I hope we can make done all instances in next time so pls report all bugs

**Comment by Mibu86** [comment]
all start testing at least 1 full instance today..if i don't get visitors..to distract me (some expected) all start with early vanilla ones

**Comment by Salja** [comment]
TestServer has Update to newst version

https://github.com/CoronaCore/OneServer/commit/893bbc62720e634f4f2cebcdebeca35eec45b9b3 https://github.com/CoronaCore/OneDatabase/commit/d2fb1651c339426bdcb40d12fa0f51f69207e1e3
https://github.com/CoronaCore/OneScripts/commit/56b71963478d5b8957329f387b59a47a31db638e

**Comment by Salja** [comment]
the dns have problems so can use for connect set realmlist 178.200.188.45

**Comment by Mibu86** [comment]
Test Server Down?

**Comment by Salja** [comment]
Yes sorry not home much rl work i hope now on weekend i have timre

**Comment by Mibu86** [comment]
np  :)

**Comment by Salja** [comment]
we payed now a server for test server will setup soon

**Comment by Mibu86** [comment]
nice...

**Comment by Salja** [comment]
Test sever is now back onlien create account under cronacore.org i will set thanfast to admin account

**Comment by Salja** [comment]
Test Server Infos will come soon here https://github.com/CoronaCore/TestServer
