### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by KevinSupertramp** [CoronaCore/Issues#177]
Hello,

First I would like to thank you for you work. Then I have a little question, how are we suppose to update our database ? As I saw you didn't make a "patch update" of your last modifications by example :)

Thanks,

**Comment by Salja** [comment]
Hey atm we dont work with updatepacks so wehn you have own things its easyer you save this on a file and replace with new database and add than you own file.

**Comment by KevinSupertramp** [comment]
Okay thanks for the quick response !

**Comment by Salja** [comment]
Wehn you need help im here my en is bad but i hope i can help xD :-)
