### ISSUE TITLE
New DBC´s, Map´s, VMap´s, MMap´s

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#179]
You need sice the last changes new DBC´s, Map´s, VMap´s, MMap´s befor questions coming =)

**Comment by Mibu86** [comment]
I need them 2 ..ass soon as i apply today changes to the core

**Comment by Salja** [comment]
New files smaller as old and faster on extract i have run 1 houer for mmaps

**Comment by q67732896** [comment]
I can not extract the new VMAPS 
I would get an error 
Can you share some of your new VMAPS it? 
Thank you

**Comment by Salja** [comment]
What error you use the new binarys ? You run as admin ? I can upload but later on day

**Comment by q67732896** [comment]
vmapExtractor.exe closed automatically extracting complete Buildings
vmap_assembler.exe not run

vmap_assembler.exe：raw data dir  vmaps dest dir

**Comment by Mibu86** [comment]
all remake my core..and test the extractors..

**Comment by ghost** [comment]
To assemble vmaps create a .bat file in your wow directory with the following content:

```
ECHO Building VMAPs
md vmaps
vmap_assembler.exe Buildings vmaps

PAUSE > NUL
```

**Comment by q67732896** [comment]
tyraela THX!!! 
I will give you a kiss

**Comment by Salja** [comment]
sice last update today need all new reextract XD have fun

**Comment by Mibu86** [comment]
O.O duh!

**Comment by Salja** [comment]
xD :-) have fun :)

**Comment by Salja** [comment]
I close here i think all have see now
