### ISSUE TITLE
Ogre Remains "Mangos One" Crash

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#18]
The Ogre Remains can be found throughout Stonemaul Ruins in Dustwallow Marsh. 
Using [Energized Totem] will summon a Stonemaul Spirit to be killed for the quest Neutral 15 [41] Spirits of Stonemaul Hold. 

As soon as u use [Energized Totem] on the remains..a Ghost of an Ogre will Spawn ..with the name " Unknown "
And immediately server crashes

**Comment by Salja** [comment]
Thanks i will check it

**Comment by Salja** [comment]
must be fixed with https://github.com/CoronaCore/OneServer/commit/03e8a496464faf6ca007012e167138df605f5e2f

**Comment by Salja** [comment]
i close here wehn you have a problem i will reopen
