### ISSUE TITLE
Bump! (other) I hire Terorists!! pls apply ...

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#180]
D:\Corona\projectone\1\dep\recastnavigation\Detour\win\VC110\Detour.vcxproj : error  : Project "D:\Corona\projectone\1\dep\recastnavigation\Detour\win\VC110\Detour.vcxproj" could not be found.
  there is only VC120 :|

**Comment by Mibu86** [comment]
So now i have to instal vs 2013 !

**Comment by Salja** [comment]
Use Vc120 file not VC110 i will fix the 110 today

**Comment by Salja** [comment]
And better you wait 1 days tomorrow i make a other vmaps update xD :-)

**Comment by Mibu86** [comment]
:| have u ever had the feeling of going from crazy to rage..ending up on rampage? i just uninstalled my visual studio..and m installing 2013 instead of my 2012 ...but UPDATE AGAIN TOMORROW! i need a terrorist to bomb you're house...gonna Google for one right away..have a nice day :))

**Comment by Salja** [comment]
You need fixes now you become fixes xD :-)

**Comment by Mibu86** [comment]
OK!  You win ...  :( no more Boom! .../sad-face/

**Comment by ghost** [comment]
A good thing you are not in the U.S., because American officials tend to dislike this kind of humor. :stuck_out_tongue_winking_eye:

**Comment by Salja** [comment]
Disslike button on github missing bump for it, and im on german haha
