### ISSUE TITLE
Im back

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#181]
So im back work goes in the next round go and post nice reports

**Comment by Mibu86** [comment]
m not back ...all be back after September 6-th
But u have so many issues opened to fix... :P

**Comment by Salja** [comment]
xD :-) yes true i will look in next days what i can make done so i will say im back and not forgot all here xD :-)

**Comment by Mibu86** [comment]
3 more day's and m done with school ..i see u haven't started fixing either ...

**Comment by Salja** [comment]
I have startet but local on pc waiting of your come bsck haha

**Comment by Salja** [comment]
Sorry much rl work the next week the project is not dead no panic xd

**Comment by Mibu86** [comment]
no panic :P i just finished all exams ...and i passed each and every one of them...  i depraved my house these day's so first i clean then i help :P ..gimme 1-2 day's

**Comment by Mibu86** [comment]
Hmm ... no more fixes?

**Comment by Salja** [comment]
last fix yesterday ?

**Comment by Salja** [comment]
Salja authored 21 hours ago
