### ISSUE TITLE
transmogrification.lua Ineffective

### ISSUE THREAD

**Issue by q67732896** [CoronaCore/Issues#182]
After I used the latest Eluna：
transmogrification.lua Ineffective
Get this error:
`2014-09-04 16:44:36 lua_scripts/transmogrification.lua:266: bad argument #1 to 'GetItemByPos' (value must be greater than 0)`

by TBC

**Comment by Rochet2** [comment]
change the -1 to 255

Better use code tags when posting rows of not normal text so it doesnt get formatted in github

**Comment by q67732896** [comment]
THX
