### ISSUE TITLE
where is it? (other)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#183]
that core u once told me u gonna keep updated for me...
Develop+warden+broadcast branches  ..i wanna start :) m to lazy to merge them atm myself

**Comment by Salja** [comment]
I will update tomorrow for you

**Comment by Mibu86** [comment]
thx all be waiting

**Comment by Mibu86** [comment]
is it done? and..is the test server up? and  when do we focus on instances?

**Comment by Salja** [comment]
Sorry im very very sick i sleep atm the most of the day i make so fast as i can

**Comment by Salja** [comment]
here updater for you https://github.com/vanilla-wow/OneServer/tree/AIO

**Comment by Mibu86** [comment]
well that core haven't been updated since jully 17 .. how m i suppose to find bugs

**Comment by Salja** [comment]
You msut be use aio branch thats extra branch for you with include warden broadcater etc https://github.com/vanilla-wow/OneServer/commits/AIO. I updatet 4 days ago

**Comment by Mibu86** [comment]
thx...m getting it now...and gonna extract those damn maps..

**Comment by Salja** [comment]
i will start some work on database and sync with new udb wotlk database update i see have some nice tbc stuff i hope we can all sync fast XD you will happy

**Comment by Mibu86** [comment]
I will be :) if it brings fixxes :) ...when do we start working on Rewriting Hyjal Summit ?

**Comment by Mibu86** [comment]
pfff.... Errors on AIO when compiling...
Error   193 error C1083: Cannot open include file: 'WardenDataStorage.h': No such file or directory D:\Corona\projectone\1\src\game\World.cpp   68  1   game
Error   194 error C1083: Cannot open include file: 'WardenWin.h': No such file or directory D:\Corona\projectone\1\src\game\WorldSession.cpp    39  1   game
Error   203 error LNK1181: cannot open input file 'D:\Corona\projectone\1\win\VC120\game__x64_Release\game.lib' D:\Corona\projectone\1\win\VC120\LINK   mangosd

Yep 2012-213 /32 bit-64 bit   all fail..

**Comment by Salja** [comment]
hmm i tested i running self branch atm strage i must check it

**Comment by Mibu86** [comment]
have you found the issue? i tried merging the branches myself and same problem...

**Comment by Salja** [comment]
no not found i test all build 32/64 debug release etc and not this error hmmmm

**Comment by Salja** [comment]
i will merge now all new stuff in this branch i hope than will working

**Comment by Salja** [comment]
i think i found the problem i push it and merge all test it now must be work

**Comment by Salja** [comment]
About hyjal is coming now in the next weeks with the new db fixes

**Comment by Salja** [comment]
Btw you never in skype online

**Comment by Mibu86** [comment]
yes i know.... i don't have Skype installed.. and i haven't bayed a webcam and a mic yet ..dunno if i ever will havent had those since i was 17 ..i don't like chating (it ends up bad..i remember i explained once)..the only thing i use for chat is trillian and it keeps all my accounts in one place...i only use it to keep in touch with friends/colleagues/and the Demonic staff .... even at my phone if i get a call the first thing that come's out of my mouth it's "what is it??!" and it better not be a curtsey call i don't like those...usually i answer those with "m fine" followed by a hangup...

**Comment by Salja** [comment]
You test the build now works all ?

**Comment by Mibu86** [comment]
Worked like a charm on 64x now :) thank you

**Comment by Mibu86** [comment]
Dont forghet to push the fixes to my lil AIO branch

**Comment by Salja** [comment]
Sure but only one fix atm so wait few days xD :-)

**Comment by Salja** [comment]
AIO is now UP To Date

**Comment by Mibu86** [comment]
thank you

**Comment by Mibu86** [comment]
need update on aio branch :P and fixing is running slow :P .... ps:just messing with you

**Comment by Salja** [comment]
Well my wife born last week my son i cant sleep atm and i need sleep for develop xD :-)

**Comment by Salja** [comment]
done

**Comment by Mibu86** [comment]
thx
