### ISSUE TITLE
Visual Target (mangos one /db)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#184]
![wowscrnshot_092214_232934](https://cloud.githubusercontent.com/assets/6356589/4363635/d4301abc-4297-11e4-9504-7fb97ddbe997.jpg)
Visual target to players...

**Comment by Salja** [comment]
must be fixed

**Comment by ghost** [comment]
@Salja:  I'm not questioning your decision if you meant to close this issue, I am just curious if you pressed the wrong button ("Close issue" instead of "Comment") because I have seen others do this before. ;-)

**Comment by Salja** [comment]
I think can be clowe thats must fixes sice the big modelid change yesterday, and wehn not we can reopen, the problem is not much ppls here what give feedback back is this working or not
