### ISSUE TITLE
Question (other/mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#186]
Should we start? i post u fix?  :P 
M sure i can find a :package:  of bugs for you

**Comment by Salja** [comment]
I will make done the 10000 fixes here what i have to push than we can start with all other, i cant say how long i needed the last time very busy and little sick xD :-) i hope i can work faster

**Comment by Salja** [comment]
i hope i can complete today some things

**Comment by Mibu86** [comment]
:+1:

**Comment by Mibu86** [comment]
i am normally a very selfish person :P "i rlly am" so : wut's up? way aren't u fixing ?

**Comment by Salja** [comment]
Atm not stabel system here so im working local and make a push rush xD :-) i working atm on all instances and 30 quests, my problem sice last paralles update for my mac is my windows not more working so i cant complie a core self xD :-) i need to fix my mac or i setup bootcemp for effective work in next time

**Comment by Mibu86** [comment]
:(

**Comment by Salja** [comment]
So pushed so e more will come i hope you now happy xD :-)

**Comment by Mibu86** [comment]
so slow on fixes :)) :-1:

**Comment by Salja** [comment]
Lol go ingame and look the bice events

**Comment by Mibu86** [comment]
i saw them..on the core...test server is up?

**Comment by Salja** [comment]
Test server is not up yet i fixed only my system what i can work in the moment for you :)

**Comment by Salja** [comment]
to slow today ? =)

**Comment by Mibu86** [comment]
To slow :) yes...wut are u currently working on? seems to me http://www.excalibur-wow.com/index.php are fixing tons ..

**Comment by Salja** [comment]
I fixed last weeks 50 quests and you say ro slow ? ;) atm not fixing im wait of my wife he born in next days a baby after this i look what we can make done.

About the other server join and look what quest working and zones spawns events i see we have 70% more stuff ;)

**Comment by Mibu86** [comment]
70% more stuff in quests...but they are paying more attention to the core..fixing items spell-power stack...etc.
&
"Congrats!!! for the baby ... wish him strength and much health"

**Comment by Salja** [comment]
Well yes but is a difference other servers have maybe payed developer, i have work long time for excalibur wow and he payed for work corona is opensource and free.

Second other servers have much more resources own server with lot of ppls for tests, corona have nothing about this ;(

Other servers have more devs corona have much but not active xD :-) 

Well thats is way im start the crowdfunding in the hope some ppls help use to make it bigger for resources atm its sad what only one ppls help us so i hope more ppl help on crowdfunding than im sure we can work much harder faster and cleanee ;)

**Comment by Mibu86** [comment]
i understand ... Free you will just have to do atm..i don't have the financial support to keep u at home fixing.. and no server population.. m doing as much as i can free 2...

**Comment by Salja** [comment]
Is just a example about pservers and opensource core projects xD :-) the core projects the fuckers the pservers make the money and come to the core projects and need the fixes.
I now we have a lot of motivation and we have a lot done this year and i hope we can make more in next time wehn all worked what i think we become a test server with lot of ppls
