### ISSUE TITLE
CoronaCore need your help!  crowdfunding

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#188]
CoronaCore need all your help for next years of devleopent we are now under crowdfunding we hope some ppls here help us and donate a small doller

http://igg.me/at/coronacore

Thanks for the support

**Comment by Salja** [comment]
sad in few days is end and only 1 donate =(

**Comment by ghost** [comment]
I would have donated more if I could, but I am currently unemployed and I don't have that much money to spend on donations. Sorry about that. I thought more people would be interested. :-\

**Comment by Salja** [comment]
You give us soo much im very happy about that i have wish some spend 1 euro to see more ppl like the work.
