### ISSUE TITLE
Witch Doctor Zum'rah (Mangos One) Server Crash

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#19]
Witch Doctor Zum'rah

This NPC can be found in Zul'Farrak.

Upon engaging in combat...a certain Troll mummy i belive (or whatever npc) will spawn from the graves (not related to Ward of Zum'rah skill that summons skeletons).
Server will hang for few seconds and than Crash.
I did int had time to check it out..if is Scriptdev2 related or just ai

**Comment by Salja** [comment]
hmmm thats i have some times ago fixed you sure you use last corona core ?

**Comment by Mibu86** [comment]
yes i compiled 3 days ago..new core..script..db all pulled from here

**Comment by Salja** [comment]
hmm i will test today strange XD

**Comment by Salja** [comment]
yepp confirm is crashed i will look and fix thanks but strange xd

**Comment by Salja** [comment]
must be fixed

**Comment by Salja** [comment]
i close here wehn you have problem i will reopen
