### ISSUE TITLE
Epoch Hunter - Old Hillsbrad Foothills(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#190]
Epoch Hunter bugs out after he has spawned his first pack of mobs and isn't attackable, ever.
![wowscrnshot_102114_055635](https://cloud.githubusercontent.com/assets/6356589/4712579/ed2f2258-58cf-11e4-83fd-932496518b4f.jpg)

**Comment by violentResolution** [comment]
Tested:

Epoch Hunter works fine for me.
Importand to know: If you just .die kill those first two NPCs
Epoch Hunter will not join the Fight.

**Comment by Salja** [comment]
well .die is bad to testing bosses the scripts have a DamageTaken Function and register only spell damge, so wehn you .die the complete script will stop better trying with damage spells .learn 11 is a good spell

**Comment by violentResolution** [comment]
I tested the boss with .damage :-D
and it works just fine.

**Comment by Salja** [comment]
yes but not on all works with damage commands some bosses have the DamageTaken function example https://github.com/CoronaCore/OneScripts/blob/develop/scripts/eastern_kingdoms/sunwell_plateau/boss_kalecgos.cpp#L362   NOTE: NOT all have it but few =)

**Comment by Mibu86** [comment]
Retested ..work's just fine.. no .die or .kill commands
My bad dont remember if i used any commands... i know commands bug the script
