### ISSUE TITLE
WTF-Water Elemental (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#194]
Mage water elemental with rage!
![wowscrnshot_102214_232145](https://cloud.githubusercontent.com/assets/6356589/4743571/3ce6d930-5a29-11e4-8473-c702fec0cc12.jpg)

rlly need a fix for this players are raging

**Comment by Salja** [comment]
Its a mistake by UnitClass Updates can you give me the entry of the elemenatr i will push a fix than fast

**Comment by Mibu86** [comment]
Entry 510 :) if u have time to fix it now pls

**Comment by Salja** [comment]
hmm i tested and not issues works fine and have mana you have last db ?

**Comment by Salja** [comment]
http://www.imgbox.de/users/public/images/AUouWaifw1.png

**Comment by Mibu86** [comment]
10/12 on my db but i dont see any updates on this npc

**Comment by Salja** [comment]
hmm i spawn him more and now i have rage too but is not on all spawns i have atm no idea but i will look now

**Comment by Mibu86** [comment]
yea just wanted to say that... first try on my test had mana all the rest rage

**Comment by Salja** [comment]
give me a moment =)

**Comment by Salja** [comment]
here the fix i push it tomorrow close wehn works thanks

UPDATE creature_template SET UnitClass = 8 WHERE entry = 510;

**Comment by Mibu86** [comment]
works fine :) thx

**Comment by Salja** [comment]
Np i push it tomorrow to the repo
