### ISSUE TITLE
Bugs CoronaCore Zero

### ISSUE THREAD

**Issue by Monstermosh** [CoronaCore/Issues#2]
The Temple of Ahn'Qiraj (aq40)- Ouro not working 
The Deadmines mr.smite not change weapon
Razorfen Downs - tutenkash not script,no respawn
The Sunken Temple - avatar of hakkar  not working
The Temple of Ahn'Qiraj (aq40)- Ouro not working
Blackwing Lair - Nefarian summon skeleton crash
Zul'Farrak- witch doctor crash server

**Comment by Salja** [comment]
pls testing http://paste2.org/IbZt16N1 for The Sunken Temple - avatar of hakkar not working

**Comment by Salja** [comment]
Zul'Farrak- witch doctor crash server
Blackwing Lair - Nefarian summon skeleton crash

Fixed in last Core Commit

**Comment by q67732897** [comment]
Zul'Aman-Nalorakk not normally kill in 2.4.3

**Comment by Salja** [comment]
@q67732897 im not understand what you mean monstermosh reports is classic 1.12.1 not 2.4.3

**Comment by Monstermosh** [comment]
http://paste2.org/xDG3tELZ    event ai script acid corected

**Comment by Salja** [comment]
Thanks i will push it soon looks all fine

**Comment by Monstermosh** [comment]
dberrors.log
2014-03-08 17:36:03 Creature (GUIDLow: 590013 Entry: 3671) has spell 13236 in `auras` field, but aura is already applied.

**Comment by Monstermosh** [comment]
NULL target for ACTION_T_CAST creature entry 7337 casting spell id 9613

**Comment by Salja** [comment]
on startup or on running server wehn you attack the creature ?

**Comment by Monstermosh** [comment]
yes

**Comment by Salja** [comment]
i will fix it today and include in next release thanks for you repo i will close here wehn you have other reports than pls make new issues open make more cleaner to open 1 issues for 1 problem ^^ =) thanks

**Comment by Monstermosh** [comment]
okay
