### ISSUE TITLE
Warsong Gulch & Arathi basin Battlemasters rong pozition (Horde in SW)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#20]
Montok Redhands 
Keldor the Lost

**Comment by Salja** [comment]
hmm im not understand the 2 npcs are in stormwind ? for me the 2 npcs in shattrath

**Comment by Mibu86** [comment]
well after recompiling i found them in SW right near the cheese shop...under one of those red battle standards that spawn on certain battleground weeks .They were also in Shattara were they belong.
  Maybe some stupid GM spawned them and left them there...then my bad..dunno for sure i just deleted them.
