### ISSUE TITLE
Npc: Scryers Cavalier (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#202]
Srlly lvl 1 :))
http://www.wowhead.com/npc=22967/scryer-cavalier
![wowscrnshot_110414_135415](https://cloud.githubusercontent.com/assets/6356589/4899211/84308df0-6419-11e4-896f-65940a70aab2.jpg)

**Comment by ghost** [comment]
If you can provide the output from the command `.npc info` on this NPC, that could highlight which properties need to be fixed on this NPC.

**Comment by Salja** [comment]
Good catch tkrokli thats i saying mibu sice month haha xD :-)

**Comment by Mibu86** [comment]
![wowscrnshot_110514_052505](https://cloud.githubusercontent.com/assets/6356589/4912304/62e16aa2-649b-11e4-8185-7496bfadced4.jpg)
![wowscrnshot_110514_052509](https://cloud.githubusercontent.com/assets/6356589/4912306/691c54cc-649b-11e4-868e-b176a452756a.jpg)

**Comment by Salja** [comment]
Hihi xD :-)

**Comment by Salja** [comment]
On weekend is fix time

**Comment by Mibu86** [comment]
i do hope so...Bug's have started to gather...some fixes are required :P

**Comment by Salja** [comment]
You must look i updatet all modelids few days ago i have worked 2 days over 30 hours on this no panic i think some more devs will come back so we can faster work

**Comment by Mibu86** [comment]
Amen!

**Comment by Salja** [comment]
fixed
