### ISSUE TITLE
Npc: Infernal? (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#203]
The infernals at "Wildhammer Stronghold&Shadomoon Village" in shadomoon valley ...not fighting Guard..and  cant be targeted by players
![wowscrnshot_110414_140020](https://cloud.githubusercontent.com/assets/6356589/4899320/6d1ecacc-641a-11e4-804a-b60682a6dda7.jpg)

**Comment by Salja** [comment]
i updatet the npc to original flag and its broken i will check it way thanks

**Comment by Salja** [comment]
ok found the problem will be fix with next backports so im close here
