### ISSUE TITLE
Major Druid issues with mana when changing forms (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#204]
here : 
![wowscrnshot_110514_170757](https://cloud.githubusercontent.com/assets/6356589/4919882/dfb6d8f2-64fd-11e4-99d7-626ce6f1b199.jpg)
notice normal druid before changing int-o owl form
And after canceling Owl form:
![wowscrnshot_110514_170807](https://cloud.githubusercontent.com/assets/6356589/4919902/0832b878-64fe-11e4-8ec6-b12c28ff9921.jpg)
Notice the mana drop...it's get fixed if buffed or dis equip /equip int stat items 
Need fix before players get pissed pls :)

**Comment by Salja** [comment]
well thats spellstecking problem thats have all emulators you cant fix fast need half core change i look for a workround but not sure yet

trinity have the same bug and other privat server too

**Comment by Mibu86** [comment]
i think it can be fixed with a .lua script ..something like ....Druid loses owl form buf mark of wild Rank 1/remove mark of wild rank 1 ...  or maybe +1 int and then remove..or reequip items. something ..anything..
maybe a .lua script that recalculates the amount of mana The druid must have based on Stats..and do .mod mana "corect amount" whenever the druid cancels  owl form..

**Comment by Salja** [comment]
pushed a fix to you aio branch test it and give feedback https://github.com/vanilla-wow/OneServer/commit/444c4a0e3e4184e8a213d24e0094e8870e9529c6

**Comment by Salja** [comment]
you test too slow

**Comment by Salja** [comment]
news ?

**Comment by Mibu86** [comment]
Tested... Works Great :+1:
