### ISSUE TITLE
important changes

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#205]
all repos have now "master" as default branch

How to use what branch
- OneServer->master->OneScripts->master->OneDatabase->master
- OneServer->develop->OneScripts->develop->OneDatabase->develop

Example for use branch develop
git clone git://github.com/CoronaCore/OneServer.git
git checkout -b develop

git clone git://github.com/CoronaCore/OneScripts.git
git checkout -b develop

git clone git://github.com/CoronaCore/OneDatabase.git
git checkout -b develop

NOTE: develop branch have now own SQL check you need to insert all updates from into your develop database https://github.com/CoronaCore/OneServer/tree/develop/sql/Develop

Pls use wehn you open a new issues the tag of branch you use

**Comment by Salja** [comment]
@Mibu86 AIO is up to date

**Comment by Mibu86** [comment]
Thank you

**Comment by Salja** [comment]
over 56 new commits pushed 2 minutes ago i will merge later with aio today

**Comment by Salja** [comment]
ok done

**Comment by ghost** [comment]
Good job, nice work. :+1:
