### ISSUE TITLE
Test Server now back

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#206]
The Test Server is now back you can create a account and its instant as admin account realmlist you found on the site.

http://www.coronacore.org/acc/

NOTE: Server is running under the develop branch

**Comment by Salja** [comment]
Test Server is now up to date with last changes

**Comment by ghost** [comment]
Nice, good to hear that. :+1:

**Comment by ghost** [comment]
Sorry for not being more active in this issue, but I haven't taken the time to research how to get a game client version 2.4.3 since I have only upgraded all the time from 2.0 (live, 2006) to WotLK. Should I just look for a game client from TPB or some other torrent site? :smiling_imp:

**Comment by Salja** [comment]
You can download here http://www.excalibur-wow.com/index.php on the legt site xD :-) 

Test server is still online the same infos on forum so i close here

**Comment by ghost** [comment]
Thanks a lot for the tip, downloading it now. :+1:

**Comment by Salja** [comment]
Hrhr cool ;)
