### ISSUE TITLE
Map/VMaps

### ISSUE THREAD

**Issue by Cobas** [CoronaCore/Issues#208]
Hey guys. I try to Compile this Core on my Linux Debian Server. Everything worked fine. But i cant find the right Maps and Vmaps. I found 1 Extractor via googel but this maps are also outdated. And the source Code did not incluede a Extractor.

**Comment by Salja** [comment]
https://github.com/CoronaCore/OneServer/tree/master/contrib/extractor_binary

for sources look at contrib folder

**Comment by Salja** [comment]
close here
