### ISSUE TITLE
Quest: You, Robot

### ISSUE THREAD

**Issue by Warchas** [CoronaCore/Issues#214]
"You, Robot" quest is bugged. It is essentially you get to command a robot to fight a bigger robot for you which you don't so you cannot complete the quest.

**Comment by Warchas** [comment]
Even if you kill the bigger robot without the robot you should get to command you will still NOT get complete on the quest.

**Comment by Salja** [comment]
pls add in next reports the entry of quest

**Comment by Salja** [comment]
fixed close
