### ISSUE TITLE
Cast Bar Disappears

### ISSUE THREAD

**Issue by ghost** [CoronaCore/Issues#215]
The player cast-bar disappears. When you cast a spell your cast-bar goes invisible when ever some other talent related spell trigger and when you get hit by an enemy. The spell will finish casting but you aren't able to see when.

quote vovk: It dissapears, when some spell triggers from tallents. Server send packet with time = 0, other word it send cast time = 0 to client & client start show this casting time. This bug should be removerd, server should not send casting time for trigger spells:
- I find my experience using CoronaCore ruined when this bug occurs are there any solutions ?

**Comment by Salja** [comment]
try and feedback

http://pastebin.com/Us44WCmZ

wehn not working change CAST_FLAG_HIDDEN_COMBATLOG to CAST_FLAG_NONE and check

**Comment by ghost** [comment]
Hello Salja thanks for the reply!

It seems to be working after some major testing with CAST_FLAG_HIDDEN_COMBATLOG. 

CAST_FLAG_NONE did just make it worse it was interupting my spellcast whenever a talent triggered, I were testing both of them just to make sure. But I'm happy to inform you that the issue does no longer persist and you can close this issue !

Thanks again for a solution and the quick reply I appreciate it :+1:

**Comment by Salja** [comment]
Than i will add to the dev branch soon thanks for Feedback
