### ISSUE TITLE
Invisibility doesn't break

### ISSUE THREAD

**Issue by ghost** [CoronaCore/Issues#217]
Class: Mage
Spell name: Invisibility
Spell id: 66

When you use invisibility it works fine, but it doesn't break when you recieve damage, drinking, eating and casting spells so it is literally a 20 seconds of god mode.

**Comment by Salja** [comment]
Atm not a idea what is the problem but i will look more of it

**Comment by Salja** [comment]
can you try pls no idea but try it XD 

http://pastebin.com/jFmzCKay

**Comment by Salja** [comment]
tested self and works wehn you have problems than post it =)

**Comment by Mibu86** [comment]
Mage invisibility do-sent work like rogue invisibility... Read tool-pit 
"Turns the caster invisible over 3 sec, reducing threat each second. While invisible, you are untargetable by enemies"
M not sure if ure supposed to take damage if ure Invisible via Mage spell or Invisibility potions
..i also remember some of the potion have a tool-pit that has something to do with "another plane" (like another dimension)
Yes Sucubus can see you ...but u cant be targeted by players..it might not be breakable by Aoe spells either.
My Rogue Invisibility(stealth/vanish) works fine..so does shadow melt but they are different from mage inv.

**Comment by ghost** [comment]
Hey sorry for the late response, it works now :-)

**Comment by Salja** [comment]
Thanks form reply yeah tested self fast xD :-) and workd
