### ISSUE TITLE
Missing Npc from Skettis(Mangos One)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#22]
Time-Lost Skettis Reaver
Time-Lost Skettis High Priest
Time-Lost Skettis Worshipper

I added them on my emu since i found them in the One database...just sitting there..correct factions..flags..working fine with the shadow elixir..etc..
M not gonna share the spawn points since i spawned them randomly and not correctly to blizzard.
I believe its a shame not to fix "skeetis" now that so many quests there have been fixed

**Comment by Salja** [comment]
Im Close here fixed
