### ISSUE TITLE
Small Gossip issue on "reset talents" for all classes (mangos one /db)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#221]
![wowscrnshot_120114_105151](https://cloud.githubusercontent.com/assets/6356589/5263756/85bc8612-7a3d-11e4-9214-610d5ef4b3e9.jpg)
happens for all classes at any trainer..

**Comment by Mibu86** [comment]
![wowscrnshot_120114_104824](https://cloud.githubusercontent.com/assets/6356589/5263774/ac1ea470-7a3d-11e4-9724-dd3af10b92f4.jpg)

**Comment by Salja** [comment]
Is the issues new ? A other ppl tell me that but not sure its a new issues

And whats goodip is missing ?

**Comment by Salja** [comment]
ok found the problem its from dualspec the gossip menu wotlk can be drop all =9
