### ISSUE TITLE
Quest:Escape from Durnholde (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#223]
Very very strange with this quest..for some players it do-sent complete ...
If i do .lookup quest on them it shows completed but in reality
![wowscrnshot_120214_181134](https://cloud.githubusercontent.com/assets/6356589/5265950/2c21a6b6-7a4f-11e4-9bb7-9f1fd1d63475.jpg)
I keept trying to complete it for them with 
.quest complete 10284 but it do-sent work..i did remove/add/complete just dosent work..
Tested it with new char..completed the way it should and it worked...i removed it..and added and completed with commands and it worked...reloged...drooped the completed quest tried with commands again..and voila it bugged for me to...
Shows up completed in .lookup quest   but in reality it looks uncompleted and i cant turn it in..
Very strange..
Players who get bugged on this cant continue with Black moras....

**Comment by Mibu86** [comment]
So any idea on this bug? script/core or wtf is it?

**Comment by Salja** [comment]
Not yet looked of this a lot of other on todo but you can delete the quest from character on catabase for a temp workround to resett the quest ?

**Comment by Salja** [comment]
I think its a db bug not big deal maybe i look today

**Comment by Salja** [comment]
tested now sice 30 mins and works very fine for me https://www.youtube.com/watch?v=r3TSjtl9rfI&feature=youtu.be

**Comment by Mibu86** [comment]
Yep players remade the quest and it completed..i think it was more of a cross-faction party bug..nvm
