### ISSUE TITLE
Autobroadcaster

### ISSUE THREAD

**Issue by IvanJeDivan** [CoronaCore/Issues#231]
Hello,
I'd like to share code for those who want an autobroadcaster.
Warm suggestions to implement it, it can also be reloaded by a command but I was too lazy to write that.

From dd524511ea67bf2e0ee44ac4fd88598f135b7f6b Mon Sep 17 00:00:00 2001
From: IvanJeDivan
Date: Mon, 8 Dec 2014 23:42:18 +0100
Subject: [PATCH] Autobroadcast Implementation

---

 sql/updates/autobroadcast.sql    | 11 ++++++++++
 src/game/Autobroadcast.cpp       | 44 ++++++++++++++++++++++++++++++++++++++++
 src/game/Autobroadcast.h         | 13 ++++++++++++
 src/game/CMakeLists.txt          |  2 ++
 src/game/Language.h              |  2 ++
 src/game/World.cpp               | 11 ++++++++++
 src/game/World.h                 |  6 ++++++
 src/mangosd/mangosd.conf.dist.in | 17 ++++++++++++++++
 win/VC120/game.vcxproj           |  2 ++
 win/VC120/game.vcxproj.filters   |  8 +++++++-
 10 files changed, 115 insertions(+), 1 deletion(-)
 create mode 100644 sql/updates/autobroadcast.sql
 create mode 100644 src/game/Autobroadcast.cpp
 create mode 100644 src/game/Autobroadcast.h

diff --git a/sql/updates/autobroadcast.sql b/sql/updates/autobroadcast.sql
new file mode 100644
index 0000000..f837bc9
--- /dev/null
+++ b/sql/updates/autobroadcast.sql
@@ -0,0 +1,11 @@
+-- ----------------------------
+-- Table structure for autobroadcast
+-- ----------------------------
+DROP TABLE IF EXISTS `autobroadcast`;
+CREATE TABLE `autobroadcast` (
-  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
-  `text` varchar(255) DEFAULT NULL COMMENT 'Text that''ll be shown in the world.',
-  PRIMARY KEY (`Id`)
  +) ENGINE=InnoDB DEFAULT CHARSET=latin1;
  +
  +INSERT INTO `mangos_string` (`entry`, `content_default`) VALUES ('2000', '[Autobroadcast]: %s')
  \ No newline at end of file
  diff --git a/src/game/Autobroadcast.cpp b/src/game/Autobroadcast.cpp
  new file mode 100644
  index 0000000..eb1a1ab
  --- /dev/null
  +++ b/src/game/Autobroadcast.cpp
  @@ -0,0 +1,44 @@
  +#include "Autobroadcast.h"
  +#include "Language.h"
  +#include "World.h"
  +#include <time.h>
  +
  +Autobroadcast::Autobroadcast()
  +{
-    _lastId = 0;
  +}
  +
  +void Autobroadcast::LoadData()
  +{
-    _time = sWorld.getConfig(CONFIG_UINT32_AUTOBROADCAST_TIMER) \* 1000;
-    QueryResult \* result = WorldDatabase.Query("SELECT \* FROM autobroadcast");
-    if (!result)
-        return;
-    do
-    {
-        Field\* field = result->Fetch();
-        _messages.push_back(std::string(field[1].GetString()));
-    } while (result->NextRow());
  +}
  +
  +void Autobroadcast::Update(uint32 diff)
  +{
-    if (!sWorld.getConfig(CONFIG_BOOL_AUTOBROADCAST_ON) || _messages.size() < 1)
-        return;
  +
-    if (_time <= diff)
-    {
-        Announce();
-        _time = sWorld.getConfig(CONFIG_UINT32_AUTOBROADCAST_TIMER) \* 1000;
-    }
-    else _time -= diff;
  +}
  +
  +void Autobroadcast::Announce()
  +{
-    if (_lastId >= _messages.size())
-        _lastId = 0;
-    sWorld.SendWorldText(LANG_AUTOBROADCAST_MESSAGE, _messages[_lastId].c_str());
-    sLog.outString("Debugging, Autobroadcast: %s", _messages[_lastId].c_str());
-    ++_lastId;
  +}
  \ No newline at end of file
  diff --git a/src/game/Autobroadcast.h b/src/game/Autobroadcast.h
  new file mode 100644
  index 0000000..5624bfc
  --- /dev/null
  +++ b/src/game/Autobroadcast.h
  @@ -0,0 +1,13 @@
  +#pragma once
  +#include <vector>
  +
  +class Autobroadcast
  +{
-    uint32 _time, _lastId;
-    std::vectorstd::string _messages;
-    public:
-        Autobroadcast();
-        void LoadData();
-        void Update(uint32 diff);
- ```
     void Announce();
  ```
  
  +};
  \ No newline at end of file
  diff --git a/src/game/CMakeLists.txt b/src/game/CMakeLists.txt
  index cd6bd11..0e17bc2 100644
  --- a/src/game/CMakeLists.txt
  +++ b/src/game/CMakeLists.txt
  @@ -298,6 +298,8 @@ set(SRC_GRP_VMAPS
  )
  
  set(SRC_GRP_WORLD_HANDLERS
-   Autobroadcast.cpp
-   Autobroadcast.h
   AccountMgr.cpp
   AccountMgr.h
   AddonHandler.cpp
  diff --git a/src/game/Language.h b/src/game/Language.h
  index d408bfd..b6ab7b7 100644
  --- a/src/game/Language.h
  +++ b/src/game/Language.h
  @@ -1017,6 +1017,8 @@ enum MangosStrings
  
   // FREE IDS                           1700-9999
-    LANG_AUTOBROADCAST_MESSAGE          = 2000
  +
   // Use for not-in-official-sources patches
   //                                    10000-10999

diff --git a/src/game/World.cpp b/src/game/World.cpp
index 10541f4..ed1bdac 100644
--- a/src/game/World.cpp
+++ b/src/game/World.cpp
@@ -115,6 +115,8 @@ World::World()
         m_configBoolValues[i] = false;

```
 m_configForceLoadMapIds = NULL;
```

+
-    Broadcaster = Autobroadcast();
  }
  
  /// World destructor
  @@ -762,6 +764,9 @@ void World::LoadConfigSettings(bool reload)
  
   setConfig(CONFIG_BOOL_PLAYER_COMMANDS, "PlayerCommands", true);
-    setConfig(CONFIG_BOOL_AUTOBROADCAST_ON, "Autobroadcast.Enabled", true);
-    setConfig(CONFIG_UINT32_AUTOBROADCAST_TIMER, "Autobroadcast.Timer", 1500);
  +
   setConfig(CONFIG_UINT32_INSTANT_LOGOUT, "InstantLogout", SEC_MODERATOR);
  
   setConfigMin(CONFIG_UINT32_GUILD_EVENT_LOG_COUNT, "Guild.EventLogRecordsCount", GUILD_EVENTLOG_MAX_RECORDS, GUILD_EVENTLOG_MAX_RECORDS);
  @@ -1397,6 +1402,10 @@ void World::SetInitialWorldSettings()
   sLog.outString("---------------------------------------");
   sLog.outString();
-    sLog.outString("Loaded autobroadcast system...");
-    Broadcaster.LoadData();
-    sLog.outString();
  +
   uint32 uStartInterval = WorldTimer::getMSTimeDiff(uStartTime, WorldTimer::getMSTime());
   sLog.outString("SERVER STARTUP TIME: %i minutes %i seconds", uStartInterval / 60000, (uStartInterval % 60000) / 1000);
   sLog.outString();
  @@ -1577,6 +1586,8 @@ void World::Update(uint32 diff)
  
   // cleanup unused GridMap objects as well as VMaps
   sTerrainMgr.Update(diff);
  +
-    Broadcaster.Update(diff);
  }
  
  namespace MaNGOS
  diff --git a/src/game/World.h b/src/game/World.h
  index 5868236..1cb719b 100644
  --- a/src/game/World.h
  +++ b/src/game/World.h
  @@ -27,6 +27,7 @@
  # include "Timer.h"
  # include "Policies/Singleton.h"
  # include "SharedDefines.h"
  
  +#include "Autobroadcast.h"
  # include <map>
  # include <set>
  
  @@ -179,6 +180,7 @@ enum eConfigUInt32Values
   CONFIG_UINT32_GUID_RESERVE_SIZE_CREATURE,
   CONFIG_UINT32_GUID_RESERVE_SIZE_GAMEOBJECT,
   CONFIG_UINT32_CREATURE_RESPAWN_AGGRO_DELAY,
-    CONFIG_UINT32_AUTOBROADCAST_TIMER,
   CONFIG_UINT32_VALUE_COUNT
  };

@@ -330,6 +332,7 @@ enum eConfigBoolValues
     CONFIG_BOOL_MMAP_ENABLED,
     CONFIG_BOOL_ELUNA_ENABLED,
     CONFIG_BOOL_PLAYER_COMMANDS,
-    CONFIG_BOOL_AUTOBROADCAST_ON,
   CONFIG_BOOL_VALUE_COUNT
  };

@@ -441,6 +444,9 @@ class World

```
     void CleanupsBeforeStop();
```
-        // Autobroadcaster
- ```
     Autobroadcast Broadcaster;
  ```
  
  +
       WorldSession\* FindSession(uint32 id) const;
       void AddSession(WorldSession\* s);
       bool RemoveSession(uint32 id);
  diff --git a/src/mangosd/mangosd.conf.dist.in b/src/mangosd/mangosd.conf.dist.in
  index af3eb30..c9b5dc4 100644
  --- a/src/mangosd/mangosd.conf.dist.in
  +++ b/src/mangosd/mangosd.conf.dist.in
  @@ -1673,3 +1673,20 @@ CharDelete.KeepDays = 30
  
  Eluna.Enabled = 1
  Eluna.ScriptPath = "lua_scripts"
  +
  +###################################################################################################################
  +# AUTOBROADCAST SETTINGS
  +#
  +#   Autobroadcast.Enabled
  +#       Enable world auto broadcast messages
  +#       Default: 1 (Enabled)
  +#                0 (Disabled)
  +#
  +#   Autobroadcast.Timer
  +#       Timer settings for message broadcast in SECONDS.
  +#       Default: 1500
  +#
  +###################################################################################################################
  +
  +Autobroadcast.Enabled = 0
  +Autobroadcast.Timer = 1500
  \ No newline at end of file
  diff --git a/win/VC120/game.vcxproj b/win/VC120/game.vcxproj
  index 6ae3328..b052452 100644
  --- a/win/VC120/game.vcxproj
  +++ b/win/VC120/game.vcxproj
  @@ -381,6 +381,7 @@
   <ClCompile Include="..\..\src\game\AuctionHouseBot\AuctionHouseBot.cpp" />
   <ClCompile Include="..\..\src\game\AuctionHouseHandler.cpp" />
   <ClCompile Include="..\..\src\game\AuctionHouseMgr.cpp" />
-    <ClCompile Include="..\..\src\game\Autobroadcast.cpp" />
   <ClCompile Include="..\..\src\game\Bag.cpp" />
   <ClCompile Include="..\..\src\game\BattleGround\BattleGround.cpp" />
   <ClCompile Include="..\..\src\game\BattleGround\BattleGroundAA.cpp" />
  @@ -554,6 +555,7 @@
   <ClInclude Include="..\..\src\game\ArenaTeam.h" />
   <ClInclude Include="..\..\src\game\AuctionHouseBot\AuctionHouseBot.h" />
   <ClInclude Include="..\..\src\game\AuctionHouseMgr.h" />
-    <ClInclude Include="..\..\src\game\Autobroadcast.h" />
   <ClInclude Include="..\..\src\game\Bag.h" />
   <ClInclude Include="..\..\src\game\BattleGround\BattleGround.h" />
   <ClInclude Include="..\..\src\game\BattleGround\BattleGroundAA.h" />
  diff --git a/win/VC120/game.vcxproj.filters b/win/VC120/game.vcxproj.filters
  index 8144e3c..a37d3ea 100644
  --- a/win/VC120/game.vcxproj.filters
  +++ b/win/VC120/game.vcxproj.filters
  @@ -547,6 +547,9 @@
   <ClCompile Include="..\..\src\game\LuaEngine\LuaFunctions.cpp">
     <Filter>LuaEngine</Filter>
   </ClCompile>
-    <ClCompile Include="..\..\src\game\Autobroadcast.cpp">
-      <Filter>World/Handlers</Filter>
-    </ClCompile>
  </ItemGroup>
  <ItemGroup>
   <ClInclude Include="..\..\src\game\AccountMgr.h">
  @@ -1105,5 +1108,8 @@
   <ClInclude Include="..\..\src\game\LuaEngine\LuaEngine.h">
     <Filter>LuaEngine</Filter>
   </ClInclude>
-    <ClInclude Include="..\..\src\game\Autobroadcast.h">
-      <Filter>World/Handlers</Filter>
-    </ClInclude>
  </ItemGroup>
  -</Project>
  +</Project>
  \ No newline at end of file
  -- 
  1.8.3.msysgit.0

**Comment by Salja** [comment]
Thanks for share bute corona have already include a autobroadcaster https://github.com/CoronaCore/OneServer/commit/bce8da2fcf6b3a8eda3f37c7f13a5015f4f33254

**Comment by IvanJeDivan** [comment]
Aww.. but I prefer modularity.

**Comment by Salja** [comment]
Well i plan to add a custom file and add all stuff in there broadccaster and some other stuff
