### ISSUE TITLE
NPC "el pollo grande" is invisible 

### ISSUE THREAD

**Issue by schell244** [CoronaCore/Issues#235]
npc id = 659 (= el pollo grande)
npc is invisible (has no display id?)

Some more information abot the npc:
El Pollo Grande is summoned by "Niby the Almighty" (npc id = 14469) in felwood upon completion of the warlock-only quest "Kroshius' Infernal Core" (quest id = 7603)

**Comment by Lumber-Jack-2** [comment]
working modelid: 589

**Comment by Salja** [comment]
Will be fix soon thanks
