### ISSUE TITLE
DB Errors

### ISSUE THREAD

**Issue by CyberMist2** [CoronaCore/Issues#239]
Branch: Develop
OneServer Rev: https://github.com/CoronaCore/OneServer/commit/f03205c1cd25e851e9e34ff5472a66d157c74016

Branch: Master
OneDatabase Rev: https://github.com/CoronaCore/OneDatabase/commit/24fd92e0e30b126958901b70915dcd381c76b017

Branch: Master
OneScripts Rev: https://github.com/CoronaCore/OneScripts/commit/94b713c24bda5e24f116dd3bba100de9cc42a79b

DB Errors: http://pastebin.com/kBD40BGB

**Comment by Salja** [comment]
Db errors atm normal will be fix after merge
