### ISSUE TITLE
Blackout Talent (mangos One)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#24]
Tested with Undead priest..with blackout talent..sometimes it affects the caster wen it procs

ps: Weird shit is happening i keep bumping int-o old bugs that have been fixed long time ago..like this one..now being active

**Comment by Salja** [comment]
I will look

**Comment by Mibu86** [comment]
any news on this issue?

**Comment by Salja** [comment]
not yet atm i switch my pc =)

**Comment by Mibu86** [comment]
rlly need a fix for this one..if u do have the time pls..

**Comment by Salja** [comment]
you can test

DELETE FROM `spell_proc_event` WHERE entry IN (15268, 15323, 15324, 15325, 15326);
INSERT INTO `spell_proc_event` VALUES
(15268, 0x20,   6,  0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0,  0,  0), -- Blackout (Rank 1)
(15323, 0x20,   6,  0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0,  0,  0), -- Blackout (Rank 2)
(15324, 0x20,   6,  0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0,  0,  0), -- Blackout (Rank 3)
(15325, 0x20,   6,  0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0,  0,  0), -- Blackout (Rank 4)
(15326, 0x20,   6,  0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0,  0,  0); -- Blackout (Rank 5)

wait of feedback

**Comment by Mibu86** [comment]
Did-int fix it..but made Blackout talent stop working at all...it no longer procs

**Comment by Salja** [comment]
Hmm ok than test now only this query pls

DELETE FROM spell_proc_event WHERE entry IN (15268, 15323, 15324, 15325, 15326);

**Comment by Mibu86** [comment]
Tested both of ure querys again for like 30 min each..here is wut i found

On this:
DELETE FROM spell_proc_event WHERE entry IN (15268, 15323, 15324, 15325, 15326);
INSERT INTO spell_proc_event VALUES
(15268, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 1)
(15323, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 2)
(15324, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 3)
(15325, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 4)
(15326, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0); -- Blackout (Rank 5)

Blackout only procs on shadow word: death and no other shadow spell dmg at all..but it procs fine! just target...and no longer procs on caster...so i think these entry's need to be written for every shadow spell that should proc blackout effect...also same thing for shadow weaving talent...because it has same issue they both proc on caster wen u use shadow word: death

on:
DELETE FROM spell_proc_event WHERE entry IN (15268, 15323, 15324, 15325, 15326);

it no longer procs at all

**Comment by Mibu86** [comment]
any news on this?

**Comment by Salja** [comment]
I have atm no idea

Btw check other issues i reply on few

**Comment by Mibu86** [comment]
well i have, one...find the line that made it proc on caster...and add one for every shadow spell it should proc...then...

DELETE FROM spell_proc_event WHERE entry IN (15268, 15323, 15324, 15325, 15326);
INSERT INTO spell_proc_event VALUES
(15268, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 1)
(15323, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 2)
(15324, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 3)
(15325, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0), -- Blackout (Rank 4)
(15326, 0x20, 6, 0x06080000, 0x00000002, 0x00000000, 0x00000000, 0x00000000, 0, 0, 0); -- Blackout (Rank 5)

and it should be fixed...
with this it only procs on shadow word :death

**Comment by Salja** [comment]
I will check this today thanks

**Comment by Mibu86** [comment]
? did u checked ?

**Comment by Salja** [comment]
I checked and i think we need small core support

**Comment by Mibu86** [comment]
Is now fixxed ..dunno how again
