### ISSUE TITLE
still @

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#247]
Watching waiting...

**Comment by Lumber-Jack-2** [comment]
wat?

**Comment by ghost** [comment]
This is such a random post. Are you just posting to say that you are tired of waiting for updates? :stuck_out_tongue_winking_eye:

**Comment by Salja** [comment]
Not net atm i Hope can fix tomorrow than come new updates

**Comment by Mibu86** [comment]
Nope m just posting to say...m checking here every once in a wile to see if my reports were fixed..and i can start retesting and posting more...

**Comment by Mibu86** [comment]
Update needed on AIO branch prt pls

**Comment by Mibu86** [comment]
any day now :)

**Comment by Mibu86** [comment]
So i see there is no more Warden/autobroodcast/mod branches...
Way?
I need them... :( 
Way not work on the core with those implemented already..this way no future trouble if you need them...
there is always the config file for ppl who dont need them to disable them..

**Comment by Salja** [comment]
autobroadcaster and mods include on develop branch, warden ist dropped bad code bad working lot of bugs and crashes from it and no time to wirte all new yet maybe later

**Comment by Mibu86** [comment]
strange ... i used all the time before... but wit few players.. no crashes on warden..but lot's of banned ppl..a lil to much i can say.

**Comment by Salja** [comment]
few ppls have much problems with connect from linux system and mac system thats makes much crashes + few ban what never use a cheat when you will use the old warden you can merge from the backup https://github.com/Salja/OneServer/tree/warden
