### ISSUE TITLE
Test-Server/BugTracker

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#249]
We have sice few weeks a own new Test-Server, Players become Instant 70 and few Commands for add items and more to test some stuff.

Please use the Tracker Addon

Tracker found here http://coronacore.org/reports.php

The Addon and Account Create found here http://coronacore.org/

**Comment by Mibu86** [comment]
OmffG This Addon is my dream!!!
If i use it..on another 2.4.3 server using you're core will it still report back here?

**Comment by Salja** [comment]
no the addon save on character.bugreport table on the server what you use the addon the addon we have sice years in the repo already tell you some time ago over it =)

**Comment by Mibu86** [comment]
were to get the sql for that addon..? i wanna use it on wowgate .
pls? all post the bugs back here

**Comment by Mibu86** [comment]
were are you Salja?

**Comment by Salja** [comment]
thats save in character.bugreports you already have it

**Comment by Mibu86** [comment]
Tryed from my GM account got this error 
.looonnnggg list....bla bla
2015-05-07 23:39:05 SQL ERROR: Field 'id' doesn't have a default value

**Comment by Salja** [comment]
the table is standart on mangos sice 2006 look into your character database and table bugreport he have id when you not delete this

**Comment by Mibu86** [comment]
well i fixed it... "auto increment" on "Id" and it works problem is...
It saves reports like crap!there onlly 3 tabs:
id/type/content

and it saves a loooooooooooooonnnngggg crapy text containing the report+all my addons+details about my pc ...etc... in the "type" tab

**Comment by Salja** [comment]
yes you need a php script what convert the string to read text same for my bug tracker thats is a php script what read the table and make a read text

**Comment by Mibu86** [comment]
do you have one? if you do all pass it to the admin to implement it in our webpage

**Comment by Salja** [comment]
https://github.com/arcemu/arcemu/tree/master/src/scripts/web/SampleBugReportReaderApp

here is one but you must rewirte for mangos table style aremu have a bit other style but for a php coder is not big deal 5 mins work
