### ISSUE TITLE
Quest "Mission: The Murketh and Shaadraz Gateways"

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#25]
Both Horde and Alliance  Quest... used to be fixed and working...no longer working..(again weird stuff)
http://www.wowhead.com/quest=10146
(mangos One)

**Comment by Salja** [comment]
What is not working the item or the count ?

**Comment by Mibu86** [comment]
well u use the item..(cast the spell right on top of the gate) nothing happens it do-sent count..

**Comment by Salja** [comment]
Hmm i have fixed long time ago and have worked i will look what it broke

**Comment by Salja** [comment]
Fixed Close
