### ISSUE TITLE
Branch:Develop merging issues

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#250]
Merging Master branch to Develop branch Fails with git on certain issues you should test it...

**Comment by Salja** [comment]
develop branch have already master include not need to merge

**Comment by Mibu86** [comment]
can you get develop branch with git? nope you get master branch....then you merge to dev .... aint workin'

**Comment by Salja** [comment]
with git checkout you can switch to the develop branch

**Comment by Rochet2** [comment]
`git checkout develop`
or
`git clone -bdevelop https://github.com/CoronaCore/OneServer.git`

**Comment by Mibu86** [comment]
ow .. O.o thank you! never did that.
