### ISSUE TITLE
Auto Broodcaster?

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#251]
none?

**Comment by ghost** [comment]
What do you mean "none?", do you mean that there is no text in the auto broadcast table, that there is a message in the server startup saying that the table is empty? That should be normal.

**Comment by Salja** [comment]
autobroadcoaster is on the develop branch include  https://github.com/CoronaCore/OneServer/commit/bce8da2fcf6b3a8eda3f37c7f13a5015f4f33254

**Comment by Mibu86** [comment]
:(
