### ISSUE TITLE
When do you start fixing again ?

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#258]
:dancer:

**Comment by Mibu86** [comment]
....? Project DEaD?

**Comment by Lumber-Jack-2** [comment]
seems to be dead, better start fixing and reporting/contributing stuff here: https://github.com/cmangos/issues

There is much activity in this project

**Comment by Lumber-Jack-2** [comment]
project is dead?

**Comment by Rochet2** [comment]
@Rushor, Im sure @Salja has found something else to do. He has been "absent" for over 6 months now.

**Comment by Salja** [comment]
Hey the Project is not very dead but im very sick the last year but im feel now better i will work again in next month on the Project and eluna Project too =)

@Rochet2 
@Rushor

**Comment by Lumber-Jack-2** [comment]
k nice to hear that :)

**Comment by Salja** [comment]
im here again

**Comment by Lumber-Jack-2** [comment]
yay

**Comment by Mibu86** [comment]
:)
