### ISSUE TITLE
Quest : Fel Spirits

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#28]
http://wowhead.com/quest=10909
u place the anchorite relic at the right place
http://wowhead.com/item=31772#.
u kill Shattered Hand i tryed all kind..
No fel spirits :) me better than yoda..
(mangos one)

**Comment by Salja** [comment]
I found a fix on my old sourcrs i will push wehn pc is back

**Comment by Mibu86** [comment]
i found some fixes to for some of the db issues here..problem is they are for the old db...and some fields are in-existent in the new ones... and i bump :)

**Comment by Salja** [comment]
The best is you have 25 friends and go instance to instance make videos we fix one instance 100% than we go to the next, wehn all done we can start with all outland quests i think more system to found bugs make it easyer to fix
