### ISSUE TITLE
The Exorcism of Colonel Jules (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#30]
It completes wen u use the Quest item http://www.wowhead.com/item=31828 on the Colonel Jules (REad item Description here :)

 "Ritual Prayer Beads"
Item Level 1
Use: Target either Anchorite Barada or the fiends released during the exorcism. (15 Sec Cooldown)

and no Fiends or any other action..
Ps:sorry for double posting this quest i didint notice..2 different issues

**Comment by Salja** [comment]
I will fix today

**Comment by Salja** [comment]
can you test the quest with this sql update and give me feedback

DELETE FROM creature_linking_template WHERE entry IN (22432);
INSERT INTO creature_linking_template (entry, map, master_entry, flag, search_range) VALUES
(22432, 530, 22431, 16, 20);

UPDATE creature_template SET InhabitType=InhabitType|4 WHERE entry=22507;
UPDATE creature_template SET MovementType=0 WHERE entry IN (22505,22507,22506);

UPDATE quest_template SET ReqSpellCast1=0 WHERE entry=10935;

DELETE FROM creature_movement_template WHERE entry IN (22431);
INSERT INTO creature_movement_template (entry, point, position_x, position_y, position_z, script_id, waittime) VALUES
(22431,1, -707.411, 2750.491, 101.591, 0, 0),
(22431,2, -709.274, 2748.262, 101.591, 0, 0),
(22431,3, -710.760, 2747.854, 101.591, 0, 1000),
(22431,4, -709.274, 2748.262, 101.591, 0, 0),
(22431,5, -707.411, 2750.491, 101.591, 0, 0),
(22431,6, -707.210, 2754.110, 101.675, 0, 1000);

**Comment by Mibu86** [comment]
Now work's fine i tested...animated..chat..and it completes wen they are done exorcising...only thing missing is the released creeps..but is good to go..anyway
