### ISSUE TITLE
Quest: Ally of the Netherwing

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#35]
http://www.wowhead.com/quest=10870/ally-of-the-netherwing#.

The dragon mount animation is horrible...ure somewhere under the dragon and it takes u lil bit ...kind way to far from were it's suppose 2
(mangos one)
minor thing but since m in the milled of reporting a major bug on this quest chain...just letting you know

**Comment by Salja** [comment]
Wehn you have the chance to make for issues video clips help really much you can make 1 mins clips and load on youtube i can fix all faster than, the most time i need to check the bug etc so wehn you can pls make small videos

**Comment by Mibu86** [comment]
i will try to ...

**Comment by Salja** [comment]
Thanks the ppl here kevin make videos for me too https://m.youtube.com/channel/UCJsrV7wLUe9WuP62CB51Qzg. Help really i can faster fix xd

**Comment by Mibu86** [comment]
pfff...u require a video? for this issue?

**Comment by Salja** [comment]
The problem is i not understand all your english xD :-)

**Comment by Mibu86** [comment]
Allow me to explain again:
When u finish this quest chain http://www.wowhead.com/quest=10804
u become Friendly with Netherwing Faction and you get this quest from "Mordenai" http://www.wowhead.com/quest=10804 it requires you to have 300 riding skill...
Now when you approach Netherwing Ledge you get transformed into Dragonmaw fel orc flying on netherdrake.. Prety cool :) and become Friendly with Dragonmaw.. so you can interact with them and do Quests for them..
The issue is that after u complete the quest chain..get 300 riding..you enter that zone and nothing..u dont get transformed into a Dragonmaw orc (that is suppose to be a disguise) there 4 u cant quest there..and you get attacked by them..
Here is a picture:
![261251](https://cloud.githubusercontent.com/assets/6356589/3447966/d851e34e-0153-11e4-91a5-0e11869888f4.jpg)
Oh my bad ..i was talking about https://github.com/CoronaCore/Issues/issues/36

**Comment by Salja** [comment]
Ah ok i understand and i can this quest let me look not sure today but tormorrow 100%

**Comment by Salja** [comment]
Question after complete all your are Friendly or not is this working so only the transform missing?

**Comment by Salja** [comment]
must be fixed pls testing https://github.com/CoronaCore/Issues/issues/36

**Comment by Salja** [comment]
ok tested self its works so close
