### ISSUE TITLE
Quest: In Service of the Illidari (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#36]
U cant Turn this Quest in because...it seems when u reach this point..(ofc u already have flying mounts skill trained)
U dont morph(desquize) into that red orc wen u enter Netherwing Ledge...so the mobs at Dragonmaw Base Camp remain hostile leaving all those quest and reputation with "netherwing" unavailable

you normally  get transformed into Dragonmaw fel orc flying on netherdrake

**Comment by Salja** [comment]
must be fixed i have not tested yet so i will close wehn you tested and confirm what is works so pls test it thanks

**Comment by Mibu86** [comment]
![wowscrnshot_070414_065345](https://cloud.githubusercontent.com/assets/6356589/3478183/cd095188-032f-11e4-9873-df87db868f64.jpg)
well u closed it...and yes is now working
