### ISSUE TITLE
Talent:Shadow Weaving (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#37]
Ally's on caster "Shadow Vulnerability" effect every time caster uses "Shadow Word : Death"

**Comment by Salja** [comment]
My new macbook broke yesterday i have a fix for it i hope next week i have my macbook back i will fix it than thanks

**Comment by Mibu86** [comment]
did it broke again? or real life issues? need you're help with this shadow talents

**Comment by Salja** [comment]
atm i work on some db stuff

**Comment by Salja** [comment]
Wehn im complete all my todo for db than i dix this issues first

**Comment by Mibu86** [comment]
which db are you working on?

**Comment by Salja** [comment]
Corona tbc db

**Comment by Mibu86** [comment]
Is now fixxed ..dunno how :))
