### ISSUE TITLE
Missing Npc from Netherstorm (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#38]
Ethereum Jailor
http://www.wowhead.com/npc=23008#drops

his already in the database but i never found him spawned on any emulators...except my own after i randomly spawned him instead of blizzlike.
He Deserves to be spawned..his a very important npc due to the fact that 
The Jailor will only drop Ethereum Prison Keys after you have finished the quest A Mission of Mercy. If you have done the quest, the drop rate will be 100%.

"Ethereum Prison Keys"
You can also use em at the prisons in Netherstorm. They are just west of Manaforge Ultris. You can see the camp on the map (mushroom looking things.
There are 5-7 prisons and you just step up to them and use you key.
Now either it will spawn a mob who can drop some pretty desent things (blue rings and good greens) or a faction guy will spawn and give you 500 rep with his faction.
There are the following factions:
*Cenarion Expedition
*Consortium
*Keepers of Time
*Lower City
*The Sha'tar
*Sporeggar

So yeah this mobs must be spawned !

**Comment by Salja** [comment]
Thanks i make next week wehn i have mc pc back

**Comment by Salja** [comment]
DONE Close here
