### ISSUE TITLE
The Deadmines 

### ISSUE THREAD

**Issue by Monstermosh** [CoronaCore/Issues#4]

**Comment by Monstermosh** [comment]
The Deadmines - Mr.Smite not change weapon

**Comment by Monstermosh** [comment]
after the murder of two rogues he does not come down to the chest
First, he must be with a Sword then with an Axe and then Mace

**Comment by Salja** [comment]
yes thats have worked some times ago i will test what is worng now

**Comment by Salja** [comment]
Fixed
