### ISSUE TITLE
Ethereum Prisons(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#42]
The Ethereum Prisons do not respawn. They spawn only on server restart.
Ethereum Prisons Game Object IDs:
184418, 184419, 184420, 184421, 184422, 184423, 184424, 184425, 184426, 184427, 184428, 184429, 184430, 184431

**Comment by Salja** [comment]
hmm on database have 10 min respawn time

**Comment by Salja** [comment]
very very strange the buffs not working wehn creature spawns and the respawn not working but is set on database need some more debug i think

**Comment by Mibu86** [comment]
it used to work on the old database ..i mean the buff ..with the correct faction... about Objects..have no ideea

**Comment by Salja** [comment]
You sure hmm nothing is changed on this sice years so thats is the strange what i mean

**Comment by Salja** [comment]
i checked old database and have faction 35 all

**Comment by Mibu86** [comment]
yes but after u add the correct factions....it works(the buff and stuff)....so the bug appeared with the new database changes.try it..put there the same factions u put in the new db and ure going to see the buff...
Somehow i notice lot's of spells are also broken now with the new db...for instance the Headless Horseman spells..."summon pumpking" and "pumpkin missle" they used to work..now they are broken..
same thing with blackout talent..
The new Db tab changes .. broken them..

**Comment by Salja** [comment]
tested on wotlk and check trinitydb ytdb etc on all is this not working XD but scriptdev2 have script support for it i cant understand atm way

**Comment by Salja** [comment]
look the npcs never touched http://www.bilder-upload.eu/upload/e0dcf0-1403989259.png

i think more not db is the problem the core have a worng commit into

**Comment by Salja** [comment]
so i tested wotlk udb/ytdb and tdb with trinitycore on all is not working

**Comment by Mibu86** [comment]
Retested ..they Respawn ..
