### ISSUE TITLE
Report to Eluna DEv (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#43]
Got no idea ..but it poped out and m just following instructions.. the rest is all Warden..
![reported](https://cloud.githubusercontent.com/assets/6356589/3407326/9506fe12-fda7-11e3-8187-af776da8b08d.png)

**Comment by Salja** [comment]
You have the newst core i think the elu a error is fixed sice few days

**Comment by Salja** [comment]
should be fixed 

Wehn you become more errors post it here https://github.com/ElunaLuaEngine/Eluna/issues

**Comment by Rochet2** [comment]
Need to know eluna version to be sure that is old version.
Otherwise update eluna and if it still happens, its a real error and then report the message to us.

Atm it looks like it is old error that was fixed already.
The error is was an issue with the error message and is not harmful. (just an invalid message)

If it still comes on newer versions, it is an actual error most likely and should be fixed.

**Comment by Mibu86** [comment]
dunno were to get Eluna version but..i complied the core like 6 day's ago so it should be the newest one..also it only spams that error on Event 18 i checked logs

**Comment by Rochet2** [comment]
> 6 day's ago

Sure : |?
The bug was fixed on 22nd, so its very close.

you can get Eluna version by for example opening git in LuaEngine folder and doing git log
See the top hash and send to us.

**Comment by Mibu86** [comment]
Author: Salja salja8840@gmail.com  2014-06-20 17:20:57
Committer: Salja salja8840@gmail.com  2014-06-20 17:25:53
Parent: 59b1dd21f76c9f56ce9521fb89404058caed64c9 (Eluna Sync)
Child:  115793c7ac9bc8d72f961c739c291328b000fef2 (Merge branch 'warden' of https://github.com/CoronaCore/OneServer)
Branches: master, remotes/origin/warden
Follows: 
Precedes: 

```
Eluna Sync
```

that's wut i found :)
and the git log 
![git log](https://cloud.githubusercontent.com/assets/6356589/3424355/166c2538-ffcc-11e3-8308-fa50d84d91eb.png)

**Comment by Salja** [comment]
Your core is from 20.6 and fixed is this on 22.6 so need to update than will work

**Comment by Mibu86** [comment]
thx

**Comment by Salja** [comment]
Np
