### ISSUE TITLE
Headless Horseman (mangos one) Hallow's End event

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#44]
Hallow's End event.
The summoning Quest no longer working...the quest autocompletes wen u accept it from pumpin...and u can turn it in to the grave.
No longer spawns.
Also ..."Summon Pumpkin Soldiers" and "Summon Pumpkin Soldier Missile" spells are broken and onlly cast animation..they dont spawn Pumpkin soldiers...they also used to work.. i know because i used to recreate "The Horseman's Blade" item that is missing in every 2.4.3 core dispite the fact that it's model exists in the db and also the proc spells..
U can read here http://www.wowhead.com/item=38175#comments   "Added in patch 2.4.3"

Probably because "Pumpkin Soldier" npc that is supose to spawn is now missing from the db ...despite the fact it has the same model as "Pumpkin fiend" that exists in the db

Also found the "The Horseman's Reins" model with trail animation 
http://www.wowhead.com/item=37012/the-horsemans-reins#.
.. that means i can also create the flying mount same Added in patch 2.4.3
Don't understand way nobody remade the cool stuff for 2.4.3 if the models are there

**Comment by Salja** [comment]
Yepp comming soon im working on it

**Comment by Salja** [comment]
Fixed

NOTE: Boss self will be fixed with next ScriptDev2 Merge pls test the quest and report i will close.

**Comment by Mibu86** [comment]
still bugged..u cant complete the summoning on the dirt mound...with the candle...u click complete but it do-sent count...and ofc no boss

**Comment by Salja** [comment]
i tested and works fine i can make a video or screens

**Comment by Mibu86** [comment]
And i stil ldont get it...way do u need a Scriptdev2 merge? the Boss used to work on the old database with sd2

**Comment by Salja** [comment]
database part here is only for spawn support of boss scriptdev2 is handel for boss spells but spawn on quest complete works fine

**Comment by Salja** [comment]
http://www.bilder-upload.eu/upload/087537-1403902406.png
http://www.bilder-upload.eu/upload/45a8f9-1403902471.png

maybe you complete already today the quest its a daily quest test it with new clean char its will be work 100%

**Comment by Mibu86** [comment]
ok'e ure right it work's...but as u said..bad scripting..he dies and that's it..no spells during encounter or split....horseman and horse .....and horseman and head.. no split at all..no spells...
Again :
"Summon Pumpkin Soldiers" and "Summon Pumpkin Soldier Missile" spells are broken"
and "Pumpkin Soldier" npc that is supose to spawn is missing from the db.... maybe it needs to be re added to the db

**Comment by Salja** [comment]
i will backport the script for the boss in few days for scriptedev2 than will work perfect =)

**Comment by Mibu86** [comment]
It wont work perfect...because of those 2 broken spells...we need core support on them and the missing minions....and since were talking about core support...fixing the Horseman mount and blade ...also requires core support...since they exist in the db but they are broken.Dunno if those 2 items and the spells work on the new emulators but if they do..maybe we can back port the code.
They are tbc content but nobody ever bother to fix them ..they exist in the mpq's of the game both models spells..everything..just broken

**Comment by Mibu86** [comment]
Have you closed this? because it requires script support..and core support for those spells he casts and if the mount and sword spells work on a newer patch core..maybe we can add suport for them to the core 2..would be nice
