### ISSUE TITLE
Help Requied with Git patch(noob issue)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#47]
I rlly dont know how to create and apply a patch with Git Bash..need a guide pls

**Comment by Rochet2** [comment]
patch or diff?
I havent used any patches, but diff can be applied with `git apply myfile.diff`
Same likely works with patches.

> `git apply` applies the patch but does not create a commit. Use `git am` to create commits from patches generated by `git-format-patch` and/or received by email.

This means that git apply should work for both .diff and .patch
It doesnt create a commit after applying.
git am works with patches only likely and will create a commit using the info from the patch file.

https://www.kernel.org/pub/software/scm/git/docs/git-apply.html
https://www.kernel.org/pub/software/scm/git/docs/git-am.html

Check out --reject in the apply documentation.

**Comment by Salja** [comment]
Patch can added by 

patch -p1 < name.patch

**Comment by Mibu86** [comment]
thx

**Comment by Salja** [comment]
Btw @Mibu86 i wait of more quest reports and db issues xD :-) im working atm on db so more reports are welcome

**Comment by Mibu86** [comment]
i needed it to apply autobroadcast function...
Edit:Reports will come ...atm...there are some important issues opened...and that's way i stoped reporting others...i fought maybe that way u will focus on those Shadow priest talents.. :P...

**Comment by Salja** [comment]
Wehn done with more db stuff i will focus on class talents and spells ok, you can add the brodcast manuell from my privat branch or maybe we can coded in lua xD :-) 

Atm not much fun of core code but yes i will look of spells in few days

**Comment by Salja** [comment]
you can self close wehn you have not more questions =)

**Comment by Mibu86** [comment]
MOre Questions!... i am so pissed :)) i dont get it...!    Git bash where?? on the Src foldeR? on the core foldeR? and tipping "git apply myfile.diff" do-sent do shit...(no such file or directory error inside the core folder/unrecognized input on the core folder...so on) how does git know were the patch is...
etc..
When i said i do not know..i meant i dunno shit ^^
Edit: Ok'e so i need to :+1: 

Copy the diff file to the root of your repository, and then do on the Repo folder:

git apply myfile.diff
....k

**Comment by Rochet2** [comment]
git apply <path>
So the file can be elsewhere, but you need to then provide the path to the file if its not where git bash is.
