### ISSUE TITLE
Quest: The Summoning Chamber(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#53]
http://www.wowhead.com/quest=10585#comments
issues when u try to use http://www.wowhead.com/item=30672 
(Elemental Displacer)  some quest mobs missing..etc...complex to fix.

**Comment by Salja** [comment]
Haha thats i have fixed too on my pc last days i test it today and push it than

Btw whats you server homepage adress ?

**Comment by Salja** [comment]
Done Feedback are Welcome

**Comment by Mibu86** [comment]
Yep good Job is working..   But...u can spam quest item in order to spam those Green flame npc's..and i wonder wut happens if an idiot finds out and spamms billions of them? could u add a condition to the use of the item? or maybe limit those npc's? to avoid spamming them?
And...
![wowscrnshot_070414_061750](https://cloud.githubusercontent.com/assets/6356589/3478043/4766d41e-032b-11e4-9692-84c45d6955f7.jpg)
That stuff is not invisibile for players :P 
Anyway it work's thank you..
Both of them..horde and alliance versions
![wowscrnshot_070414_062935](https://cloud.githubusercontent.com/assets/6356589/3478060/7cae2a14-032b-11e4-9b08-906ca5c79406.jpg)

**Comment by Salja** [comment]
I will fix the trigger and take alook of item spawn not sure atm to stop it but we found a fix for it
