### ISSUE TITLE
Quest: Our Boy Wants To Be A Skyguard Ranger (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#57]
http://www.wowhead.com/quest=11030
how it should be:
Collect 10 Apexis shards from the Bash'ir guys at Bash'ir Landing in Blade's Edge (51,14). Once you get those, fly down to Forge Camp Terror and turn them in to the Fel Crystalforge (29,81).

At  Fel Crystalforge u Bump! not working :-1: 
![wowscrnshot_070114_231922](https://cloud.githubusercontent.com/assets/6356589/3449074/a69299c6-0161-11e4-90f3-90282051de2a.jpg)

Also the flask is not Bop and very useful in Grull Raids

**Comment by Mibu86** [comment]
Also Do-sent give any reputation with Ogrila Faction if u Self complete it as a GM and turn it back in...m sure it do-sent give to players even if it was fixed

**Comment by Salja** [comment]
Fixed
