### ISSUE TITLE
Quest: A Father's Duty(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#59]
http://www.wowhead.com/quest=11061
Missing "Bash'ir crystalforge" object ...even if u add it...also not working same issue like https://github.com/CoronaCore/Issues/issues/57
also the only way to obtain http://www.wowhead.com/item=32601 ...
![wowscrnshot_070214_002451](https://cloud.githubusercontent.com/assets/6356589/3449420/2952f4ce-0166-11e4-8786-3caa6c01b93a.jpg)
Where it should be..
Also: Not Rewarding it's Reputation with Ogrilla when u turn it back...(after u self complete it as a GM)
(mangos one)

**Comment by Salja** [comment]
some note for me the object is spawned but on worng place

**Comment by Salja** [comment]
Fixed
