### ISSUE TITLE
Quest: A Fel Whip For Gahk (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#60]
http://www.wowhead.com/quest=11079#.
Totally not working..
same as the Flask Rewarding quests...all the way to the Quest object then "Bump!"
![wowscrnshot_070214_002914](https://cloud.githubusercontent.com/assets/6356589/3449473/d64b5cca-0166-11e4-9dad-701de030330b.jpg)

Ogrilla Quests are totally broken all over..nobody ever bothered to fix them..is like a Broken Faction everyone has abandoned...even if it has extremely good rewards
Ps: First quest that rewards rep. on selfcomplete

**Comment by Salja** [comment]
Fixed
