### ISSUE TITLE
Goosip: Commander Ameer(minor)(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#75]
missing gossip..when u click "what are the ethereum"
![wowscrnshot_070314_010827](https://cloud.githubusercontent.com/assets/6356589/3463099/91485108-0235-11e4-9f36-c3bd2f49bc9a.jpg)

**Comment by Salja** [comment]
Can you wehn you make screenshot ingame .npc info so what i can see the entry of the npc make a lot faster in next time for me xD :-)

**Comment by Salja** [comment]
Fixed
