### ISSUE TITLE
Mana Tide Totem

### ISSUE THREAD

**Issue by zwisus** [CoronaCore/Issues#8]
http://paste2.org/6w12YgB8

**Comment by Salja** [comment]
can you say what is worng and what you fix =) make much easyer to check it hehe

**Comment by zwisus** [comment]
Totem::IsImmuneToSpellEffect   miss Mana Tide Totem，so Mana Tide Totem is invalid.

Mana Tide Totem spell id 16190

**Comment by Salja** [comment]
thanks i remember i think is missing part of old fix from here https://github.com/mangos-one/server-old/issues/20 and https://github.com/mangos-one/server-old/commit/bd31a09d7cd402100bd035b0eafce92e520b693b

i will check it today and push it thanks for share
