### ISSUE TITLE
Quest: Fel Reavers, No Thanks!(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#81]
http://www.wowhead.com/quest=10855
Bugged and very strange...
You get the 5 items required u give them to the fel reaver ...it shows Quest completed but it remains uncompleted and with blue mark like it's a repeatable quest.
![wowscrnshot_070314_020154](https://cloud.githubusercontent.com/assets/6356589/3463662/3782d2e4-023d-11e4-928f-bf800b860892.jpg)

**Comment by Salja** [comment]
Fixed
