### ISSUE TITLE
Note 4 Salja

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#84]
You asked for it :)) there u go..a sea of bugs...and if you want more.. then know .. i barely scratched the surface.

**Comment by Salja** [comment]
Sure give me all what you have its good what we have all bugs on one place so i can fix it time by time all :) btw what is your server domain?

**Comment by Mibu86** [comment]
well i did-int start my own server after all...just made peace with my old Admin..so atm m still fixing for http://demonicwow.com  for free and for fun :) like always..sadly i don't get much players on..they rather play on crappy private servers for the big population.
I just got back to them when i poped up again to bother yea
wish we had more ppl like you working on this emulator...i always been a fan of tbc..and now Mangos announced they aren't working on this project anymore... sad... many ppl loved this patch and they still do..
Got a Dev rank but my dev skills suck...m more of a deducting person and that helps me understand how certain things work.

**Comment by Salja** [comment]
Sounds good i ask only so i can take a look in the forum i think you have a bug tracker so wehn you forgot to report here or i have not more things to fixing i can look xD :-) 

Just a not for you some time ago i port the original blizzard feedback ui addon so players can report bugs and the bugs will be saved into characters.bugreport tabelle only a small php script is missing to read the reports in right formart than i think make lot easyer for you and me wehn you test it https://github.com/CoronaCore/Tools/tree/master/OneTools/AddOns

Go ingame than you will see the blizzard button as example you can click on a quest than you can report it or npc item spell etc, he will save the report to characters.bugreports i have found a php script to read the tabelle than but must be fixed for mangos i have not big php skill so wehn you can ir have a friend you can take a look on it http://arcemu.org/forums/index.php?showtopic=26707

**Comment by Mibu86** [comment]
my admin is php friendly i will inform him

**Comment by Salja** [comment]
Well CoronaCore is based on mangos and CoronaCore will be active develop on tbc you see in moment i work alone on all we have only devs for the lus engine but all other database core scripts i make alone so not much all done but active, i think the ppls not can CoronaCore i have only a post on ac-web and emudevs so i think more ppls will come to help wehn make some more posts on other forums, i will help ppls to understand the source code so ppls can help fixing the best start is the database i think a lot can fix it in database so wehn you have questions you can ask me

**Comment by Salja** [comment]
Haha i think thats is good for you report issues on github rules http://forum.demonicwow.com/index.php?/topic/13-how-to-report-quest-bugg/
