### ISSUE TITLE
Nagrand Spawn Timer(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#86]
wut is that and way i can see it with GM off?
![wowscrnshot_070314_024516](https://cloud.githubusercontent.com/assets/6356589/3463934/0c419bc8-0243-11e4-808a-c5fb87405fc9.jpg)

**Comment by Salja** [comment]
Good question xD :-) i will fix tomorrow cool what you make a lot of reports so i have tomorrow some work i go sleep thanks for reports

**Comment by Mibu86** [comment]
Well look into halaa Pvp event also ..the 4 griffon spots cant be controlled from what i know..and also pvp do-sent reward http://www.wowhead.com/item=26045#created-by-spell

**Comment by Salja** [comment]
Fixed
