### ISSUE TITLE
Autobroodcast Patch (other reQuest)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#87]
if i were to ask you to help me with an Auto broadcast Patch so it wont give me Error when i do 
Git aplly
The error:

Welcome to Git (version 1.9.4-preview20140611)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

mibu@MIBU-PC /D/Corona/projectone/1 ((bad920c...))
$ git apply auto.patch
auto.patch:86: trailing whitespace.

auto.patch:87: tab in indent.
        static uint32 autobroadcaston = 0;
error: patch failed: src/game/Language.h:943
error: src/game/Language.h: patch does not apply
error: patch failed: src/game/World.cpp:62
error: src/game/World.cpp: patch does not apply
error: patch failed: src/game/World.h:82
error: src/game/World.h: patch does not apply
error: patch failed: src/mangosd/mangosd.conf.dist.in:1607
error: src/mangosd/mangosd.conf.dist.in: patch does not apply

And the patch link:

https://code.google.com/p/cntc2/source/browse/magos-patches/Auto-Broadcast-v2.patch?r=8bf39389698192874cacbdfb2d5fdee7b4b967fe

That's the patch m talking about... my admin is applying it manually all the time.. kinda pisses me off..hes to lazy to fix it inside the .patch file..
And i hate begging him all the time to do it..so i can apply it fast and easy whenever i recompile
Can you help? and maybe merge it into a branch? 
U can see it working in some of my SS ...but i want to Recompile for the Eluna updates...and i cant reach him (we talk like 40 min in 3 day's ..but i have direct access to the sql and server box) and i m also not 100% sure his applying it without active conflicts.
Ps:
This is wut i do when m bored :))
![wowscrnshot_070414_072818](https://cloud.githubusercontent.com/assets/6356589/3478299/b75fa216-0333-11e4-85a9-2d8e896dff0b.jpg)

**Comment by Salja** [comment]
I create on weekwen for you a branch with autobroadcaster

**Comment by Mibu86** [comment]
thank you..

**Comment by Salja** [comment]
Done here the link to the branch https://github.com/CoronaCore/OneServer/commits/custom

wehn you only need a patch file than save this to auto.patch https://github.com/CoronaCore/OneServer/commit/84e3f77c78cd4b2adcb29622c87fbff7a9943678.patch

you can patch than with        patch -p1 < auto.patch

**Comment by Mibu86** [comment]
I patched but:
IT came out like this 

Welcome to Git (version 1.9.4-preview20140611)

mibu@MIBU-PC /D/Corona/projectone/1 ((bad920c...))
$ patch -p1 < auto.patch
patching file `sql/custom/mangos_autobroadcast.sql'
patching file`sql/custom/realmd_autobroadcast.sql'
patching file `src/game/Language.h'
patching file`src/game/World.cpp'
Hunk #1 FAILED at 65.
Hunk #2 succeeded at 1315 (offset 9 lines).
Hunk #3 succeeded at 1535 (offset 4 lines).
Hunk #4 succeeded at 1944 (offset 9 lines).
1 out of 4 hunks FAILED -- saving rejects to src/game/World.cpp.rej
patching file `src/game/World.h'
Hunk #2 succeeded at 448 (offset 6 lines).
patching file`src/mangosd/mangosd.conf.dist.in'
Hunk #1 succeeded at 1697 with fuzz 1 (offset 50 lines).
patch unexpectedly ends in middle of line

**Comment by Salja** [comment]
Yeah you use playerbot too and on world cpp use the same lines so you need to add the https://github.com/CoronaCore/OneServer/commit/84e3f77c78cd4b2adcb29622c87fbff7a9943678#diff-b32f1858cfb04ed3727c85b4aee11e7fR68  On world.cpp self

**Comment by Mibu86** [comment]
I don't have the player-bot branch ..what i have is Develop and Warden branch merged...and now i added broadcast ..some notepad ++ work but is done.(not done..).

**Comment by Salja** [comment]
Than come from warden use same line xd

**Comment by Mibu86** [comment]
and Tons of errors when compiling.. :|

**Comment by Mibu86** [comment]
Cant it be Done on Separate lines? (Found issue)

**Comment by Salja** [comment]
Btw about autobroadcast way do you not clone the server apply the patch and wehn new updates coming than you pull it than you dont need all time apply the patch

**Comment by Mibu86** [comment]
i merged my core (develop+warden) with broodcast..corrected manually some stupid changes to Objectmgr.cpp that  fuck's up the merge..and now is working fine..i should be able to pull new updates
