### ISSUE TITLE
Quest:Sabotage the Warp-Gate! (ruined because friendlly quest adds)(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#89]
![wowscrnshot_070414_103339](https://cloud.githubusercontent.com/assets/6356589/3479265/1d1e9a92-034f-11e4-91d6-7338b29c2ffa.jpg)
![wowscrnshot_070414_103510](https://cloud.githubusercontent.com/assets/6356589/3479268/2792b8a0-034f-11e4-9d97-ef129617b635.jpg)
![wowscrnshot_070414_104102](https://cloud.githubusercontent.com/assets/6356589/3479272/2c87a91a-034f-11e4-815c-0257ef8e5ea8.jpg)
id's 20399,20402,20403

**Comment by Salja** [comment]
The question is spawn the mobs by this quest wehn yes im sure the faction 35 is correct and need a script to change faction on spawn

**Comment by Mibu86** [comment]
Yes ....pfff...Way? cant you just change their Faction in the db? and it will be fixxed? way complicate with script here?

**Comment by Salja** [comment]
sure will be fixed but i must check for the right fix XD not all can be fix only by change faction wehn its not blizzlike some creatures need a small db script to change faction on spawn from 35 to 14 as example

**Comment by Salja** [comment]
For a temp fix you can use

Update creature_template set FactionAlliance=14, FactionHorde=14 where entry in (20399,20402,20403);

**Comment by Salja** [comment]
Fixed
