### ISSUE TITLE
Blessing of Light spell description

### ISSUE THREAD

**Issue by zwisus** [CoronaCore/Issues#9]
http://paste2.org/nDwAehMI

**Comment by Salja** [comment]
can you say what is worng and what you fix =) make much easyer to check it hehe

**Comment by zwisus** [comment]
Blessing of Light
Rank 1
85 mana
30 yd range
Instant
Places a Blessing on the friendly target, increasing the effects of Holy Light spells used on the target by up to 210 and the effect Flash of Light spells used on the target by up to 60. Lasts 5 min. Players may only have one Blessing on them per Paladin at any one time.

Worng : Not increasing the effects of Holy Light spells used on the target.

If a paladin has aura Blessing of Light,the paladin will increase healing bouns.

**Comment by Salja** [comment]
Thanks
