### ISSUE TITLE
The Strange Red Imp!(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#90]
Netherstorm is full of this visible trigger for non GM
![wowscrnshot_070414_100717](https://cloud.githubusercontent.com/assets/6356589/3479310/99c1f440-034f-11e4-9b9b-395b55ced4e0.jpg)
![wowscrnshot_070414_100551](https://cloud.githubusercontent.com/assets/6356589/3479312/a29d14dc-034f-11e4-8029-a17dd7d175a9.jpg)
![wowscrnshot_070414_104023](https://cloud.githubusercontent.com/assets/6356589/3479315/b16a7284-034f-11e4-9792-c5128bb8c61e.jpg)

**Comment by Salja** [comment]
Thats is good what you report on old tbcdb is all trigger spawns worng so i have change the system but all triggers need now a update thanks for report i will look what i can change all today

**Comment by Salja** [comment]
I will help you to understand what is worng

On old system have on creature_template ModelId1 and ModelId3 same records of the ModelId but that is worng we need to update ModelId3 to 0 and add ModelId2 a other trigger ModelId, ModelId1 need not to change i hope you understand now the system more

**Comment by Salja** [comment]
here some update examples

UPDATE creature_template SET ModelId3=0, ModelId4=0 WHERE entry = 21348;
UPDATE creature_template SET ModelId3=0, ModelId4=0 WHERE entry = 21262;
UPDATE creature_template SET ModelId3=0, ModelId4=0 WHERE entry = 21261;
UPDATE creature_template SET ModelId3=0, ModelId4=0 WHERE entry = 21310;
UPDATE creature_template SET ModelId2=11686, ModelId3=0 WHERE entry = 21321;
UPDATE creature_template SET ModelId2=19595, ModelId3=0 WHERE entry = 21353;

but i will not push yet i will update first more today than i push it

**Comment by Mibu86** [comment]
ok'e

**Comment by Salja** [comment]
Fixed and some more wehn you found more so pls report
