### ISSUE TITLE
Shadowmoon Valley

### ISSUE THREAD

**Issue by Salja** [CoronaCore/Issues#93]
Shadowmoon Valley Rework

Quests
NPC
Spawns
Texts
Waypoints
Gossips
Events

**Comment by Salja** [comment]
Status 20%

**Comment by Salja** [comment]
Status 60%

**Comment by Mibu86** [comment]
:+1:

**Comment by Salja** [comment]
I hope i can done this weekend xD :-)  but you can test it looks very nice

**Comment by Salja** [comment]
Status 70% Done

**Comment by Mibu86** [comment]
And this is suppose to clean all existing bugs in Shadowmoon Valley? m asking because some of the spells certain npc's are using or certain quest item spells..might be broken inside the core..so a db Rewrite wouldn't fix it..and how the ..... r u doing it so fast ..lol

**Comment by Salja** [comment]
Fix not all but missing spawns, events, waypoints and and and

**Comment by Salja** [comment]
as example thats fix visual things npc run and say texts npc casts on other npc

here 2 videos from me
https://www.youtube.com/watch?v=WPeAEYXDWRk
https://www.youtube.com/watch?v=KoFsJIy8v4w

wehn you need real gameplay than you need all, on other servers npcs stay on same place and make nothing thats broke the gameplay really

**Comment by Salja** [comment]
Status 80% done and good playtable if you found bugs pls report here

**Comment by Mibu86** [comment]
it includes BT instance?

**Comment by Salja** [comment]
No only the outdoor shadowmoon valley bt coming soon with hyjal rework

**Comment by Salja** [comment]
i make rework of all zones and instances so first zones and quests etc than instances but all comming in next time you see i can work fast ^^

**Comment by Mibu86** [comment]
I lov wut you did! in Shadowmoon! I start testing the place..right away

**Comment by Salja** [comment]
Tomorrow come the rest of shadowmoon valley

**Comment by Salja** [comment]
i hope i can complete +- on weekend complete shadowmoon valley

**Comment by Salja** [comment]
now 98% done =)

**Comment by Mibu86** [comment]
nice (did u check way warden is causing lagg on that core u linked me?)

**Comment by Salja** [comment]
No the warden system need a rewirte and i think warden have not to much check now to using for live servers you running warden longer ? Or first sice few days

**Comment by Mibu86** [comment]
Well i have been running it since the last 3 months..didn't had any issues until now..yes is not 100% efficient..but it keeps certain hack's away..for certain players...for some it gives error when trying to check them..dont know way...maybe firewall maybe they can spoof them self..or maybe is because of 32bit-64bit encoding... but kicking certain weh users from the login screen is good for discouraging them at haking..
So yeah i would like to keep this warden inside the core if posible

**Comment by Salja** [comment]
The strange is nothing is changed on warden system and wehn you running sice month and have not the problem than is very strange maybe a recompile helps ?

**Comment by Salja** [comment]
I think a simple anticheat system is better i will look i have some old patches maybe i can rewirte one and i thinks help more the most hack is fly and speed

**Comment by Mibu86** [comment]
i tryed like 3 recompile...issue came with the last Elunna updates..any chance it might have created conflicts with the Warden system?
Edit:Maybe issue with the Handlers

**Comment by Salja** [comment]
Good question i can ask rochet for this issues but eluna files is seperart hmm

**Comment by Rochet2** [comment]
The eluna updates didnt really add anything anywhere.
They simply removed unnecessary stuff added by eluna all around the core with includes.

No warden or other has been touched and no new type names or similar should be in use, which would make it very very unlikely to be that we caused some conflict suddenly.

Hmm..
Can you send some version hashes of the commits you tested on that were fine and that were lagging?
Just to try locating what could have caused such behavior if anything.
Make a separate issue maybe.

**Comment by Salja** [comment]
i close here pls reopen a new issues only for the warden things i will bump in next days the new db release so must close here XD last shadowmoon valley fixes will come time by time

**Comment by Salja** [comment]
Im sure im done here only few quests need fix it few misc things and some clean and enter shadowmoon valley event missing the last part 20 ist comming soon
