### ISSUE TITLE
Dragonmaw Illusion(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#94]
![wowscrnshot_070714_223639](https://cloud.githubusercontent.com/assets/6356589/3500718/09b6f794-060e-11e4-899d-782fc3083d99.jpg)
Have been fixed and now works when u enter the island region 
But!.... it fails inside the mines...u get debuffed in that area..and u shouldnt..the disquised is supposed to stay inside the mine 2.
![wowscrnshot_070714_223823](https://cloud.githubusercontent.com/assets/6356589/3500737/4817d422-060e-11e4-9803-47699d173338.jpg)

**Comment by Salja** [comment]
Ok fix come tomorrow

**Comment by Mibu86** [comment]
Btw all keep posting issues here..there are easier for me to post..and for you to fix...i belive..i dont wanna make a huge topic there :package:  incoming..

**Comment by Salja** [comment]
Ok

**Comment by Salja** [comment]
Fixed
