### ISSUE TITLE
Quest:A slow Death (mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#96]
http://www.wowhead.com/quest=11020#comments
the Fel Glands drops are missing

Drop From ( Felboars )
http://www.wowhead.com/?npc=21878

---

Drop From ( felfire Diemetradon )
http://www.wowhead.com/?npc=21408

Not only this But the quest item do-sent combine with them
here:
![wowscrnshot_070714_225936](https://cloud.githubusercontent.com/assets/6356589/3501015/4b0dc940-0611-11e4-9f61-dc93cdff98fd.jpg)

RETESTED:
MY bad it works...there is no combining u just need to have the glands in ure inventory and everything else works here SS:
![wowscrnshot_070714_230151](https://cloud.githubusercontent.com/assets/6356589/3501039/aa514cce-0611-11e4-9937-088af7fb3ce6.jpg)
![wowscrnshot_070714_230153](https://cloud.githubusercontent.com/assets/6356589/3501041/b0c956b4-0611-11e4-8fb7-2d9c06360a68.jpg)
So just the item drop needs fix

**Comment by Salja** [comment]
very strange the item is into the database but have a condition what you must have the quest 11020 in your log than drop the item from the npcs on the database have 100% drop rate so i think the conditions system is buggy ? hmm 

temp fix im sure its works can you test it ?

UPDATE creature_loot_template SET condition_id = 0 WHERE item = 32502;

**Comment by Mibu86** [comment]
will test it later..got 2 players on :))

**Comment by Salja** [comment]
Fixed
