### ISSUE TITLE
Quest: Lord Illidan Stormrage(mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#99]
The quest works but the animation is total crap...illidan image pops out walking away..without saying one word.
http://www.wowhead.com/quest=11108#comments
This is a Complex encounter with escape to shatara..should be smth like this

Overlord Mor'ghor says: Come, <playername>. Lord Stormrage awaits.
Overlord Mor'ghor yells: Warriors of Dragonmaw, gather 'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord <playername>!
Overlord Mor'ghor says: Lord Illidan will be here shortly.
Illidan Stormrage appears.
Overlord Mor'ghor yells: All hail Lord Illidan!
Overlord Mor'ghor says: Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory!
Illidan Stormrage says: What is the meaning of this, Mor'ghor?
Overlord Mor'ghor says: But... My lord, I do not understand. <playername>... He is the orc that has...
Illidan Stormrage says: SILENCE!
Illidan Stormrage says: Blathering idiot. You incomprehensibly incompetent buffoon...
Illidan Stormrage says: THIS is your hero?
Illidan Stormrage says: You have been deceived, imbecile.
Illidan Stormrage says: This... whole... operation... HAS BEEN COMPROMISED!
Illidan Stormrage says: I expect to see this insect's carcass in pieces in my lair within the hour. Fail and you will suffer a fate so much worse than death.
Overlord Mor'ghor says: It will be done, my lord.
Illidan Stormrage takes his leave.
Overlord Mor'ghor says: So you thought to make a fool of Mor'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance.
Yarzill the Merc says: You will not harm the boy, Mor'ghor! Quickly, <playername>, climb on my back!

In this event Yarzill the Merc, a goblin quest giver located in Dragonmaw Base Camp, reveals his true nature: Yarzill is actually one of the older dragons of Netherwings.

The quest leads to these six, giving an option to select the color of a Netherwing Drake of your very own.
http://www.wowhead.com/?quest=11109
http://www.wowhead.com/?quest=11110
http://www.wowhead.com/?quest=11111
http://www.wowhead.com/?quest=11112
http://www.wowhead.com/?quest=11113
http://www.wowhead.com/?quest=11114

**Comment by Salja** [comment]
pls test it now

**Comment by Salja** [comment]
works now blizzlike so close here nice quest

**Comment by Mibu86** [comment]
99% fixxed..only the small error at the end when 
Yarzill the Merc says: You will not harm the boy, Mor'ghor! Quickly, , climb on my back!
..u click him for gossip ...select "let's escape"  and it say's "ure to far away from the taxy vendor"
Normally  Yarzill the Merc turns to a dragon mount and fly's u back to Shatara..but lol
That's to complicated to fix :) it would require a fly path ..etc..

**Comment by Salja** [comment]
Hmm for me works i fly to shattrath you turn gm off ? And tested with gm on to ?

Or you mean from shattrath back to the shadowmoon valley

**Comment by Salja** [comment]
im sure i tested this quest again and works for me with fly
